/*
 * This file is generated by jOOQ.
 */
package com.baeldung.jooq.introduction.db.tables;


import com.baeldung.jooq.introduction.db.Localdev;
import com.baeldung.jooq.introduction.db.tables.records.CkEnvPropUniqueRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CkEnvPropUnique extends TableImpl<CkEnvPropUniqueRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>LOCALDEV.CK_ENV_PROP_UNIQUE</code>
     */
    public static final CkEnvPropUnique CK_ENV_PROP_UNIQUE = new CkEnvPropUnique();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CkEnvPropUniqueRecord> getRecordType() {
        return CkEnvPropUniqueRecord.class;
    }

    /**
     * The column <code>LOCALDEV.CK_ENV_PROP_UNIQUE.SERVICE_ID</code>.
     */
    public final TableField<CkEnvPropUniqueRecord, Object> SERVICE_ID = createField(DSL.name("SERVICE_ID"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.CK_ENV_PROP_UNIQUE.PROFILE_ID</code>.
     */
    public final TableField<CkEnvPropUniqueRecord, Object> PROFILE_ID = createField(DSL.name("PROFILE_ID"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.CK_ENV_PROP_UNIQUE.PROP_ID</code>.
     */
    public final TableField<CkEnvPropUniqueRecord, Object> PROP_ID = createField(DSL.name("PROP_ID"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.CK_ENV_PROP_UNIQUE.TYPE_PROPERTY</code>.
     */
    public final TableField<CkEnvPropUniqueRecord, Object> TYPE_PROPERTY = createField(DSL.name("TYPE_PROPERTY"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.CK_ENV_PROP_UNIQUE.STAND</code>.
     */
    public final TableField<CkEnvPropUniqueRecord, Object> STAND = createField(DSL.name("STAND"), SQLDataType.OTHER, this, "");

    private CkEnvPropUnique(Name alias, Table<CkEnvPropUniqueRecord> aliased) {
        this(alias, aliased, null);
    }

    private CkEnvPropUnique(Name alias, Table<CkEnvPropUniqueRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view());
    }

    /**
     * Create an aliased <code>LOCALDEV.CK_ENV_PROP_UNIQUE</code> table reference
     */
    public CkEnvPropUnique(String alias) {
        this(DSL.name(alias), CK_ENV_PROP_UNIQUE);
    }

    /**
     * Create an aliased <code>LOCALDEV.CK_ENV_PROP_UNIQUE</code> table reference
     */
    public CkEnvPropUnique(Name alias) {
        this(alias, CK_ENV_PROP_UNIQUE);
    }

    /**
     * Create a <code>LOCALDEV.CK_ENV_PROP_UNIQUE</code> table reference
     */
    public CkEnvPropUnique() {
        this(DSL.name("CK_ENV_PROP_UNIQUE"), null);
    }

    public <O extends Record> CkEnvPropUnique(Table<O> child, ForeignKey<O, CkEnvPropUniqueRecord> key) {
        super(child, key, CK_ENV_PROP_UNIQUE);
    }

    @Override
    public Schema getSchema() {
        return Localdev.LOCALDEV;
    }

    @Override
    public CkEnvPropUnique as(String alias) {
        return new CkEnvPropUnique(DSL.name(alias), this);
    }

    @Override
    public CkEnvPropUnique as(Name alias) {
        return new CkEnvPropUnique(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CkEnvPropUnique rename(String name) {
        return new CkEnvPropUnique(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CkEnvPropUnique rename(Name name) {
        return new CkEnvPropUnique(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Object, Object, Object, Object, Object> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
