/*
 * This file is generated by jOOQ.
 */
package com.baeldung.jooq.introduction.db.tables;


import com.baeldung.jooq.introduction.db.Localdev;
import com.baeldung.jooq.introduction.db.tables.records.DatabasechangelogRecord;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row14;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Databasechangelog extends TableImpl<DatabasechangelogRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>LOCALDEV.DATABASECHANGELOG</code>
     */
    public static final Databasechangelog DATABASECHANGELOG = new Databasechangelog();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DatabasechangelogRecord> getRecordType() {
        return DatabasechangelogRecord.class;
    }

    /**
     * The column <code>LOCALDEV.DATABASECHANGELOG.ID</code>.
     */
    public final TableField<DatabasechangelogRecord, Object> ID = createField(DSL.name("ID"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.DATABASECHANGELOG.AUTHOR</code>.
     */
    public final TableField<DatabasechangelogRecord, Object> AUTHOR = createField(DSL.name("AUTHOR"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.DATABASECHANGELOG.FILENAME</code>.
     */
    public final TableField<DatabasechangelogRecord, Object> FILENAME = createField(DSL.name("FILENAME"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.DATABASECHANGELOG.DATEEXECUTED</code>.
     */
    public final TableField<DatabasechangelogRecord, LocalDateTime> DATEEXECUTED = createField(DSL.name("DATEEXECUTED"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>LOCALDEV.DATABASECHANGELOG.ORDEREXECUTED</code>.
     */
    public final TableField<DatabasechangelogRecord, Object> ORDEREXECUTED = createField(DSL.name("ORDEREXECUTED"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.DATABASECHANGELOG.EXECTYPE</code>.
     */
    public final TableField<DatabasechangelogRecord, Object> EXECTYPE = createField(DSL.name("EXECTYPE"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.DATABASECHANGELOG.MD5SUM</code>.
     */
    public final TableField<DatabasechangelogRecord, Object> MD5SUM = createField(DSL.name("MD5SUM"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.DATABASECHANGELOG.DESCRIPTION</code>.
     */
    public final TableField<DatabasechangelogRecord, Object> DESCRIPTION = createField(DSL.name("DESCRIPTION"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.DATABASECHANGELOG.COMMENTS</code>.
     */
    public final TableField<DatabasechangelogRecord, Object> COMMENTS = createField(DSL.name("COMMENTS"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.DATABASECHANGELOG.TAG</code>.
     */
    public final TableField<DatabasechangelogRecord, Object> TAG = createField(DSL.name("TAG"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.DATABASECHANGELOG.LIQUIBASE</code>.
     */
    public final TableField<DatabasechangelogRecord, Object> LIQUIBASE = createField(DSL.name("LIQUIBASE"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.DATABASECHANGELOG.CONTEXTS</code>.
     */
    public final TableField<DatabasechangelogRecord, Object> CONTEXTS = createField(DSL.name("CONTEXTS"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.DATABASECHANGELOG.LABELS</code>.
     */
    public final TableField<DatabasechangelogRecord, Object> LABELS = createField(DSL.name("LABELS"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.DATABASECHANGELOG.DEPLOYMENT_ID</code>.
     */
    public final TableField<DatabasechangelogRecord, Object> DEPLOYMENT_ID = createField(DSL.name("DEPLOYMENT_ID"), SQLDataType.OTHER, this, "");

    private Databasechangelog(Name alias, Table<DatabasechangelogRecord> aliased) {
        this(alias, aliased, null);
    }

    private Databasechangelog(Name alias, Table<DatabasechangelogRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>LOCALDEV.DATABASECHANGELOG</code> table reference
     */
    public Databasechangelog(String alias) {
        this(DSL.name(alias), DATABASECHANGELOG);
    }

    /**
     * Create an aliased <code>LOCALDEV.DATABASECHANGELOG</code> table reference
     */
    public Databasechangelog(Name alias) {
        this(alias, DATABASECHANGELOG);
    }

    /**
     * Create a <code>LOCALDEV.DATABASECHANGELOG</code> table reference
     */
    public Databasechangelog() {
        this(DSL.name("DATABASECHANGELOG"), null);
    }

    public <O extends Record> Databasechangelog(Table<O> child, ForeignKey<O, DatabasechangelogRecord> key) {
        super(child, key, DATABASECHANGELOG);
    }

    @Override
    public Schema getSchema() {
        return Localdev.LOCALDEV;
    }

    @Override
    public Databasechangelog as(String alias) {
        return new Databasechangelog(DSL.name(alias), this);
    }

    @Override
    public Databasechangelog as(Name alias) {
        return new Databasechangelog(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Databasechangelog rename(String name) {
        return new Databasechangelog(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Databasechangelog rename(Name name) {
        return new Databasechangelog(name, null);
    }

    // -------------------------------------------------------------------------
    // Row14 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row14<Object, Object, Object, LocalDateTime, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object> fieldsRow() {
        return (Row14) super.fieldsRow();
    }
}
