/*
 * This file is generated by jOOQ.
 */
package com.baeldung.jooq.introduction.db.tables;


import com.baeldung.jooq.introduction.db.Keys;
import com.baeldung.jooq.introduction.db.Localdev;
import com.baeldung.jooq.introduction.db.tables.records.DictServiceRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DictService extends TableImpl<DictServiceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>LOCALDEV.DICT_SERVICE</code>
     */
    public static final DictService DICT_SERVICE = new DictService();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DictServiceRecord> getRecordType() {
        return DictServiceRecord.class;
    }

    /**
     * The column <code>LOCALDEV.DICT_SERVICE.ID</code>.
     */
    public final TableField<DictServiceRecord, Object> ID = createField(DSL.name("ID"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.DICT_SERVICE.MAIN_CLASS</code>.
     */
    public final TableField<DictServiceRecord, Object> MAIN_CLASS = createField(DSL.name("MAIN_CLASS"), SQLDataType.OTHER, this, "");

    private DictService(Name alias, Table<DictServiceRecord> aliased) {
        this(alias, aliased, null);
    }

    private DictService(Name alias, Table<DictServiceRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>LOCALDEV.DICT_SERVICE</code> table reference
     */
    public DictService(String alias) {
        this(DSL.name(alias), DICT_SERVICE);
    }

    /**
     * Create an aliased <code>LOCALDEV.DICT_SERVICE</code> table reference
     */
    public DictService(Name alias) {
        this(alias, DICT_SERVICE);
    }

    /**
     * Create a <code>LOCALDEV.DICT_SERVICE</code> table reference
     */
    public DictService() {
        this(DSL.name("DICT_SERVICE"), null);
    }

    public <O extends Record> DictService(Table<O> child, ForeignKey<O, DictServiceRecord> key) {
        super(child, key, DICT_SERVICE);
    }

    @Override
    public Schema getSchema() {
        return Localdev.LOCALDEV;
    }

    @Override
    public UniqueKey<DictServiceRecord> getPrimaryKey() {
        return Keys.PK_DICT_SERVICE;
    }

    @Override
    public List<UniqueKey<DictServiceRecord>> getKeys() {
        return Arrays.<UniqueKey<DictServiceRecord>>asList(Keys.PK_DICT_SERVICE);
    }

    @Override
    public DictService as(String alias) {
        return new DictService(DSL.name(alias), this);
    }

    @Override
    public DictService as(Name alias) {
        return new DictService(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DictService rename(String name) {
        return new DictService(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DictService rename(Name name) {
        return new DictService(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Object, Object> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
