/*
 * This file is generated by jOOQ.
 */
package com.baeldung.jooq.introduction.db.tables;


import com.baeldung.jooq.introduction.db.Keys;
import com.baeldung.jooq.introduction.db.Localdev;
import com.baeldung.jooq.introduction.db.tables.records.DictAbstractGraphNodeRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DictAbstractGraphNode extends TableImpl<DictAbstractGraphNodeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>LOCALDEV.DICT_ABSTRACT_GRAPH_NODE</code>
     */
    public static final DictAbstractGraphNode DICT_ABSTRACT_GRAPH_NODE = new DictAbstractGraphNode();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DictAbstractGraphNodeRecord> getRecordType() {
        return DictAbstractGraphNodeRecord.class;
    }

    /**
     * The column <code>LOCALDEV.DICT_ABSTRACT_GRAPH_NODE.GRAPH_ID</code>.
     */
    public final TableField<DictAbstractGraphNodeRecord, Object> GRAPH_ID = createField(DSL.name("GRAPH_ID"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.DICT_ABSTRACT_GRAPH_NODE.NODE_TYPE</code>.
     */
    public final TableField<DictAbstractGraphNodeRecord, Object> NODE_TYPE = createField(DSL.name("NODE_TYPE"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.DICT_ABSTRACT_GRAPH_NODE.NODE_ID</code>.
     */
    public final TableField<DictAbstractGraphNodeRecord, Object> NODE_ID = createField(DSL.name("NODE_ID"), SQLDataType.OTHER, this, "");

    private DictAbstractGraphNode(Name alias, Table<DictAbstractGraphNodeRecord> aliased) {
        this(alias, aliased, null);
    }

    private DictAbstractGraphNode(Name alias, Table<DictAbstractGraphNodeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>LOCALDEV.DICT_ABSTRACT_GRAPH_NODE</code> table reference
     */
    public DictAbstractGraphNode(String alias) {
        this(DSL.name(alias), DICT_ABSTRACT_GRAPH_NODE);
    }

    /**
     * Create an aliased <code>LOCALDEV.DICT_ABSTRACT_GRAPH_NODE</code> table reference
     */
    public DictAbstractGraphNode(Name alias) {
        this(alias, DICT_ABSTRACT_GRAPH_NODE);
    }

    /**
     * Create a <code>LOCALDEV.DICT_ABSTRACT_GRAPH_NODE</code> table reference
     */
    public DictAbstractGraphNode() {
        this(DSL.name("DICT_ABSTRACT_GRAPH_NODE"), null);
    }

    public <O extends Record> DictAbstractGraphNode(Table<O> child, ForeignKey<O, DictAbstractGraphNodeRecord> key) {
        super(child, key, DICT_ABSTRACT_GRAPH_NODE);
    }

    @Override
    public Schema getSchema() {
        return Localdev.LOCALDEV;
    }

    @Override
    public UniqueKey<DictAbstractGraphNodeRecord> getPrimaryKey() {
        return Keys.PK_DICT_ABSTRACT_GRAPH_NODE;
    }

    @Override
    public List<UniqueKey<DictAbstractGraphNodeRecord>> getKeys() {
        return Arrays.<UniqueKey<DictAbstractGraphNodeRecord>>asList(Keys.PK_DICT_ABSTRACT_GRAPH_NODE);
    }

    @Override
    public DictAbstractGraphNode as(String alias) {
        return new DictAbstractGraphNode(DSL.name(alias), this);
    }

    @Override
    public DictAbstractGraphNode as(Name alias) {
        return new DictAbstractGraphNode(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DictAbstractGraphNode rename(String name) {
        return new DictAbstractGraphNode(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DictAbstractGraphNode rename(Name name) {
        return new DictAbstractGraphNode(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Object, Object, Object> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
