/*
 * This file is generated by jOOQ.
 */
package com.baeldung.jooq.introduction.db.tables;


import com.baeldung.jooq.introduction.db.Keys;
import com.baeldung.jooq.introduction.db.Localdev;
import com.baeldung.jooq.introduction.db.tables.records.DictServiceNodeRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DictServiceNode extends TableImpl<DictServiceNodeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>LOCALDEV.DICT_SERVICE_NODE</code>
     */
    public static final DictServiceNode DICT_SERVICE_NODE = new DictServiceNode();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DictServiceNodeRecord> getRecordType() {
        return DictServiceNodeRecord.class;
    }

    /**
     * The column <code>LOCALDEV.DICT_SERVICE_NODE.SERVICE_ID</code>.
     */
    public final TableField<DictServiceNodeRecord, Object> SERVICE_ID = createField(DSL.name("SERVICE_ID"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.DICT_SERVICE_NODE.PROFILE_ID</code>.
     */
    public final TableField<DictServiceNodeRecord, Object> PROFILE_ID = createField(DSL.name("PROFILE_ID"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.DICT_SERVICE_NODE.NODE_TYPE</code>.
     */
    public final TableField<DictServiceNodeRecord, Object> NODE_TYPE = createField(DSL.name("NODE_TYPE"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.DICT_SERVICE_NODE.ID</code>.
     */
    public final TableField<DictServiceNodeRecord, Object> ID = createField(DSL.name("ID"), SQLDataType.OTHER, this, "");

    private DictServiceNode(Name alias, Table<DictServiceNodeRecord> aliased) {
        this(alias, aliased, null);
    }

    private DictServiceNode(Name alias, Table<DictServiceNodeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>LOCALDEV.DICT_SERVICE_NODE</code> table reference
     */
    public DictServiceNode(String alias) {
        this(DSL.name(alias), DICT_SERVICE_NODE);
    }

    /**
     * Create an aliased <code>LOCALDEV.DICT_SERVICE_NODE</code> table reference
     */
    public DictServiceNode(Name alias) {
        this(alias, DICT_SERVICE_NODE);
    }

    /**
     * Create a <code>LOCALDEV.DICT_SERVICE_NODE</code> table reference
     */
    public DictServiceNode() {
        this(DSL.name("DICT_SERVICE_NODE"), null);
    }

    public <O extends Record> DictServiceNode(Table<O> child, ForeignKey<O, DictServiceNodeRecord> key) {
        super(child, key, DICT_SERVICE_NODE);
    }

    @Override
    public Schema getSchema() {
        return Localdev.LOCALDEV;
    }

    @Override
    public UniqueKey<DictServiceNodeRecord> getPrimaryKey() {
        return Keys.PK_DICT_SERVICE_NODE;
    }

    @Override
    public List<UniqueKey<DictServiceNodeRecord>> getKeys() {
        return Arrays.<UniqueKey<DictServiceNodeRecord>>asList(Keys.PK_DICT_SERVICE_NODE);
    }

    @Override
    public DictServiceNode as(String alias) {
        return new DictServiceNode(DSL.name(alias), this);
    }

    @Override
    public DictServiceNode as(Name alias) {
        return new DictServiceNode(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DictServiceNode rename(String name) {
        return new DictServiceNode(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DictServiceNode rename(Name name) {
        return new DictServiceNode(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Object, Object, Object, Object> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
