/*
 * This file is generated by jOOQ.
 */
package com.baeldung.jooq.introduction.db.tables;


import com.baeldung.jooq.introduction.db.Keys;
import com.baeldung.jooq.introduction.db.Localdev;
import com.baeldung.jooq.introduction.db.tables.records.DictKafkaPropertyGrpRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DictKafkaPropertyGrp extends TableImpl<DictKafkaPropertyGrpRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>LOCALDEV.DICT_KAFKA_PROPERTY_GRP</code>
     */
    public static final DictKafkaPropertyGrp DICT_KAFKA_PROPERTY_GRP = new DictKafkaPropertyGrp();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DictKafkaPropertyGrpRecord> getRecordType() {
        return DictKafkaPropertyGrpRecord.class;
    }

    /**
     * The column <code>LOCALDEV.DICT_KAFKA_PROPERTY_GRP.ID</code>.
     */
    public final TableField<DictKafkaPropertyGrpRecord, Object> ID = createField(DSL.name("ID"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.DICT_KAFKA_PROPERTY_GRP.TYPE_READ</code>.
     */
    public final TableField<DictKafkaPropertyGrpRecord, Object> TYPE_READ = createField(DSL.name("TYPE_READ"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.DICT_KAFKA_PROPERTY_GRP.DESCRIPTION</code>.
     */
    public final TableField<DictKafkaPropertyGrpRecord, Object> DESCRIPTION = createField(DSL.name("DESCRIPTION"), SQLDataType.OTHER, this, "");

    private DictKafkaPropertyGrp(Name alias, Table<DictKafkaPropertyGrpRecord> aliased) {
        this(alias, aliased, null);
    }

    private DictKafkaPropertyGrp(Name alias, Table<DictKafkaPropertyGrpRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>LOCALDEV.DICT_KAFKA_PROPERTY_GRP</code> table reference
     */
    public DictKafkaPropertyGrp(String alias) {
        this(DSL.name(alias), DICT_KAFKA_PROPERTY_GRP);
    }

    /**
     * Create an aliased <code>LOCALDEV.DICT_KAFKA_PROPERTY_GRP</code> table reference
     */
    public DictKafkaPropertyGrp(Name alias) {
        this(alias, DICT_KAFKA_PROPERTY_GRP);
    }

    /**
     * Create a <code>LOCALDEV.DICT_KAFKA_PROPERTY_GRP</code> table reference
     */
    public DictKafkaPropertyGrp() {
        this(DSL.name("DICT_KAFKA_PROPERTY_GRP"), null);
    }

    public <O extends Record> DictKafkaPropertyGrp(Table<O> child, ForeignKey<O, DictKafkaPropertyGrpRecord> key) {
        super(child, key, DICT_KAFKA_PROPERTY_GRP);
    }

    @Override
    public Schema getSchema() {
        return Localdev.LOCALDEV;
    }

    @Override
    public UniqueKey<DictKafkaPropertyGrpRecord> getPrimaryKey() {
        return Keys.PK_DICT_KAFKA_PROPERTY_GRP;
    }

    @Override
    public List<UniqueKey<DictKafkaPropertyGrpRecord>> getKeys() {
        return Arrays.<UniqueKey<DictKafkaPropertyGrpRecord>>asList(Keys.PK_DICT_KAFKA_PROPERTY_GRP);
    }

    @Override
    public DictKafkaPropertyGrp as(String alias) {
        return new DictKafkaPropertyGrp(DSL.name(alias), this);
    }

    @Override
    public DictKafkaPropertyGrp as(Name alias) {
        return new DictKafkaPropertyGrp(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DictKafkaPropertyGrp rename(String name) {
        return new DictKafkaPropertyGrp(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DictKafkaPropertyGrp rename(Name name) {
        return new DictKafkaPropertyGrp(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Object, Object, Object> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
