/*
 * This file is generated by jOOQ.
 */
package com.baeldung.jooq.introduction.db.tables;


import com.baeldung.jooq.introduction.db.Localdev;
import com.baeldung.jooq.introduction.db.tables.records.DictServiceProfileRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DictServiceProfile extends TableImpl<DictServiceProfileRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>LOCALDEV.DICT_SERVICE_PROFILE</code>
     */
    public static final DictServiceProfile DICT_SERVICE_PROFILE = new DictServiceProfile();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DictServiceProfileRecord> getRecordType() {
        return DictServiceProfileRecord.class;
    }

    /**
     * The column <code>LOCALDEV.DICT_SERVICE_PROFILE.ID</code>.
     */
    public final TableField<DictServiceProfileRecord, Object> ID = createField(DSL.name("ID"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.DICT_SERVICE_PROFILE.MAIN_CLASS</code>.
     */
    public final TableField<DictServiceProfileRecord, Object> MAIN_CLASS = createField(DSL.name("MAIN_CLASS"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.DICT_SERVICE_PROFILE.PROFILE_ID</code>.
     */
    public final TableField<DictServiceProfileRecord, Object> PROFILE_ID = createField(DSL.name("PROFILE_ID"), SQLDataType.OTHER, this, "");

    private DictServiceProfile(Name alias, Table<DictServiceProfileRecord> aliased) {
        this(alias, aliased, null);
    }

    private DictServiceProfile(Name alias, Table<DictServiceProfileRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view());
    }

    /**
     * Create an aliased <code>LOCALDEV.DICT_SERVICE_PROFILE</code> table reference
     */
    public DictServiceProfile(String alias) {
        this(DSL.name(alias), DICT_SERVICE_PROFILE);
    }

    /**
     * Create an aliased <code>LOCALDEV.DICT_SERVICE_PROFILE</code> table reference
     */
    public DictServiceProfile(Name alias) {
        this(alias, DICT_SERVICE_PROFILE);
    }

    /**
     * Create a <code>LOCALDEV.DICT_SERVICE_PROFILE</code> table reference
     */
    public DictServiceProfile() {
        this(DSL.name("DICT_SERVICE_PROFILE"), null);
    }

    public <O extends Record> DictServiceProfile(Table<O> child, ForeignKey<O, DictServiceProfileRecord> key) {
        super(child, key, DICT_SERVICE_PROFILE);
    }

    @Override
    public Schema getSchema() {
        return Localdev.LOCALDEV;
    }

    @Override
    public DictServiceProfile as(String alias) {
        return new DictServiceProfile(DSL.name(alias), this);
    }

    @Override
    public DictServiceProfile as(Name alias) {
        return new DictServiceProfile(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DictServiceProfile rename(String name) {
        return new DictServiceProfile(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DictServiceProfile rename(Name name) {
        return new DictServiceProfile(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Object, Object, Object> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
