/*
 * This file is generated by jOOQ.
 */
package com.baeldung.jooq.introduction.db.tables;


import com.baeldung.jooq.introduction.db.Keys;
import com.baeldung.jooq.introduction.db.Localdev;
import com.baeldung.jooq.introduction.db.tables.records.DictFlinkPropValueRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DictFlinkPropValue extends TableImpl<DictFlinkPropValueRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>LOCALDEV.DICT_FLINK_PROP_VALUE</code>
     */
    public static final DictFlinkPropValue DICT_FLINK_PROP_VALUE = new DictFlinkPropValue();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DictFlinkPropValueRecord> getRecordType() {
        return DictFlinkPropValueRecord.class;
    }

    /**
     * The column <code>LOCALDEV.DICT_FLINK_PROP_VALUE.SERVICE_ID</code>.
     */
    public final TableField<DictFlinkPropValueRecord, Object> SERVICE_ID = createField(DSL.name("SERVICE_ID"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.DICT_FLINK_PROP_VALUE.PROFILE_ID</code>.
     */
    public final TableField<DictFlinkPropValueRecord, Object> PROFILE_ID = createField(DSL.name("PROFILE_ID"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.DICT_FLINK_PROP_VALUE.PROP_ID</code>.
     */
    public final TableField<DictFlinkPropValueRecord, Object> PROP_ID = createField(DSL.name("PROP_ID"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.DICT_FLINK_PROP_VALUE.PROP_VALUE</code>.
     */
    public final TableField<DictFlinkPropValueRecord, Object> PROP_VALUE = createField(DSL.name("PROP_VALUE"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.DICT_FLINK_PROP_VALUE.IS_FUNCTION</code>.
     */
    public final TableField<DictFlinkPropValueRecord, Object> IS_FUNCTION = createField(DSL.name("IS_FUNCTION"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.DICT_FLINK_PROP_VALUE.FUNCTION_ID</code>.
     */
    public final TableField<DictFlinkPropValueRecord, Object> FUNCTION_ID = createField(DSL.name("FUNCTION_ID"), SQLDataType.OTHER, this, "");

    private DictFlinkPropValue(Name alias, Table<DictFlinkPropValueRecord> aliased) {
        this(alias, aliased, null);
    }

    private DictFlinkPropValue(Name alias, Table<DictFlinkPropValueRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>LOCALDEV.DICT_FLINK_PROP_VALUE</code> table reference
     */
    public DictFlinkPropValue(String alias) {
        this(DSL.name(alias), DICT_FLINK_PROP_VALUE);
    }

    /**
     * Create an aliased <code>LOCALDEV.DICT_FLINK_PROP_VALUE</code> table reference
     */
    public DictFlinkPropValue(Name alias) {
        this(alias, DICT_FLINK_PROP_VALUE);
    }

    /**
     * Create a <code>LOCALDEV.DICT_FLINK_PROP_VALUE</code> table reference
     */
    public DictFlinkPropValue() {
        this(DSL.name("DICT_FLINK_PROP_VALUE"), null);
    }

    public <O extends Record> DictFlinkPropValue(Table<O> child, ForeignKey<O, DictFlinkPropValueRecord> key) {
        super(child, key, DICT_FLINK_PROP_VALUE);
    }

    @Override
    public Schema getSchema() {
        return Localdev.LOCALDEV;
    }

    @Override
    public UniqueKey<DictFlinkPropValueRecord> getPrimaryKey() {
        return Keys.PK_DICT_FLINK_PROP_VALUE;
    }

    @Override
    public List<UniqueKey<DictFlinkPropValueRecord>> getKeys() {
        return Arrays.<UniqueKey<DictFlinkPropValueRecord>>asList(Keys.PK_DICT_FLINK_PROP_VALUE);
    }

    @Override
    public DictFlinkPropValue as(String alias) {
        return new DictFlinkPropValue(DSL.name(alias), this);
    }

    @Override
    public DictFlinkPropValue as(Name alias) {
        return new DictFlinkPropValue(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DictFlinkPropValue rename(String name) {
        return new DictFlinkPropValue(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DictFlinkPropValue rename(Name name) {
        return new DictFlinkPropValue(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Object, Object, Object, Object, Object, Object> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
