/*
 * This file is generated by jOOQ.
 */
package com.baeldung.jooq.introduction.db.tables;


import com.baeldung.jooq.introduction.db.Keys;
import com.baeldung.jooq.introduction.db.Localdev;
import com.baeldung.jooq.introduction.db.tables.records.DictKafkaPropValueRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DictKafkaPropValue extends TableImpl<DictKafkaPropValueRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>LOCALDEV.DICT_KAFKA_PROP_VALUE</code>
     */
    public static final DictKafkaPropValue DICT_KAFKA_PROP_VALUE = new DictKafkaPropValue();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DictKafkaPropValueRecord> getRecordType() {
        return DictKafkaPropValueRecord.class;
    }

    /**
     * The column <code>LOCALDEV.DICT_KAFKA_PROP_VALUE.GRP_ID</code>.
     */
    public final TableField<DictKafkaPropValueRecord, Object> GRP_ID = createField(DSL.name("GRP_ID"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.DICT_KAFKA_PROP_VALUE.TYPE_PROP</code>.
     */
    public final TableField<DictKafkaPropValueRecord, Object> TYPE_PROP = createField(DSL.name("TYPE_PROP"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.DICT_KAFKA_PROP_VALUE.PROP_ID</code>.
     */
    public final TableField<DictKafkaPropValueRecord, Object> PROP_ID = createField(DSL.name("PROP_ID"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.DICT_KAFKA_PROP_VALUE.PROP_VALUE</code>.
     */
    public final TableField<DictKafkaPropValueRecord, Object> PROP_VALUE = createField(DSL.name("PROP_VALUE"), SQLDataType.OTHER, this, "");

    private DictKafkaPropValue(Name alias, Table<DictKafkaPropValueRecord> aliased) {
        this(alias, aliased, null);
    }

    private DictKafkaPropValue(Name alias, Table<DictKafkaPropValueRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>LOCALDEV.DICT_KAFKA_PROP_VALUE</code> table reference
     */
    public DictKafkaPropValue(String alias) {
        this(DSL.name(alias), DICT_KAFKA_PROP_VALUE);
    }

    /**
     * Create an aliased <code>LOCALDEV.DICT_KAFKA_PROP_VALUE</code> table reference
     */
    public DictKafkaPropValue(Name alias) {
        this(alias, DICT_KAFKA_PROP_VALUE);
    }

    /**
     * Create a <code>LOCALDEV.DICT_KAFKA_PROP_VALUE</code> table reference
     */
    public DictKafkaPropValue() {
        this(DSL.name("DICT_KAFKA_PROP_VALUE"), null);
    }

    public <O extends Record> DictKafkaPropValue(Table<O> child, ForeignKey<O, DictKafkaPropValueRecord> key) {
        super(child, key, DICT_KAFKA_PROP_VALUE);
    }

    @Override
    public Schema getSchema() {
        return Localdev.LOCALDEV;
    }

    @Override
    public UniqueKey<DictKafkaPropValueRecord> getPrimaryKey() {
        return Keys.PK_DICT_KAFKA_PROP_VALUE;
    }

    @Override
    public List<UniqueKey<DictKafkaPropValueRecord>> getKeys() {
        return Arrays.<UniqueKey<DictKafkaPropValueRecord>>asList(Keys.PK_DICT_KAFKA_PROP_VALUE);
    }

    @Override
    public DictKafkaPropValue as(String alias) {
        return new DictKafkaPropValue(DSL.name(alias), this);
    }

    @Override
    public DictKafkaPropValue as(Name alias) {
        return new DictKafkaPropValue(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DictKafkaPropValue rename(String name) {
        return new DictKafkaPropValue(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DictKafkaPropValue rename(Name name) {
        return new DictKafkaPropValue(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Object, Object, Object, Object> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
