/*
 * This file is generated by jOOQ.
 */
package com.baeldung.jooq.introduction.db.tables;


import com.baeldung.jooq.introduction.db.Localdev;
import com.baeldung.jooq.introduction.db.tables.records.DictServiceInsRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DictServiceIns extends TableImpl<DictServiceInsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>LOCALDEV.DICT_SERVICE_INS</code>
     */
    public static final DictServiceIns DICT_SERVICE_INS = new DictServiceIns();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DictServiceInsRecord> getRecordType() {
        return DictServiceInsRecord.class;
    }

    /**
     * The column <code>LOCALDEV.DICT_SERVICE_INS.GRAPH_ID</code>.
     */
    public final TableField<DictServiceInsRecord, Object> GRAPH_ID = createField(DSL.name("GRAPH_ID"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.DICT_SERVICE_INS.SERVICE_ID</code>.
     */
    public final TableField<DictServiceInsRecord, Object> SERVICE_ID = createField(DSL.name("SERVICE_ID"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.DICT_SERVICE_INS.PROFILE_ID</code>.
     */
    public final TableField<DictServiceInsRecord, Object> PROFILE_ID = createField(DSL.name("PROFILE_ID"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.DICT_SERVICE_INS.MAIN_CLASS</code>.
     */
    public final TableField<DictServiceInsRecord, Object> MAIN_CLASS = createField(DSL.name("MAIN_CLASS"), SQLDataType.OTHER, this, "");

    private DictServiceIns(Name alias, Table<DictServiceInsRecord> aliased) {
        this(alias, aliased, null);
    }

    private DictServiceIns(Name alias, Table<DictServiceInsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view());
    }

    /**
     * Create an aliased <code>LOCALDEV.DICT_SERVICE_INS</code> table reference
     */
    public DictServiceIns(String alias) {
        this(DSL.name(alias), DICT_SERVICE_INS);
    }

    /**
     * Create an aliased <code>LOCALDEV.DICT_SERVICE_INS</code> table reference
     */
    public DictServiceIns(Name alias) {
        this(alias, DICT_SERVICE_INS);
    }

    /**
     * Create a <code>LOCALDEV.DICT_SERVICE_INS</code> table reference
     */
    public DictServiceIns() {
        this(DSL.name("DICT_SERVICE_INS"), null);
    }

    public <O extends Record> DictServiceIns(Table<O> child, ForeignKey<O, DictServiceInsRecord> key) {
        super(child, key, DICT_SERVICE_INS);
    }

    @Override
    public Schema getSchema() {
        return Localdev.LOCALDEV;
    }

    @Override
    public DictServiceIns as(String alias) {
        return new DictServiceIns(DSL.name(alias), this);
    }

    @Override
    public DictServiceIns as(Name alias) {
        return new DictServiceIns(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DictServiceIns rename(String name) {
        return new DictServiceIns(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DictServiceIns rename(Name name) {
        return new DictServiceIns(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Object, Object, Object, Object> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
