/*
 * This file is generated by jOOQ.
 */
package com.baeldung.jooq.introduction.db.tables;


import com.baeldung.jooq.introduction.db.Keys;
import com.baeldung.jooq.introduction.db.Localdev;
import com.baeldung.jooq.introduction.db.tables.records.DictKafkaPropValueByStandRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DictKafkaPropValueByStand extends TableImpl<DictKafkaPropValueByStandRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>LOCALDEV.DICT_KAFKA_PROP_VALUE_BY_STAND</code>
     */
    public static final DictKafkaPropValueByStand DICT_KAFKA_PROP_VALUE_BY_STAND = new DictKafkaPropValueByStand();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DictKafkaPropValueByStandRecord> getRecordType() {
        return DictKafkaPropValueByStandRecord.class;
    }

    /**
     * The column <code>LOCALDEV.DICT_KAFKA_PROP_VALUE_BY_STAND.GRP_ID</code>.
     */
    public final TableField<DictKafkaPropValueByStandRecord, Object> GRP_ID = createField(DSL.name("GRP_ID"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.DICT_KAFKA_PROP_VALUE_BY_STAND.TYPE_PROP</code>.
     */
    public final TableField<DictKafkaPropValueByStandRecord, Object> TYPE_PROP = createField(DSL.name("TYPE_PROP"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.DICT_KAFKA_PROP_VALUE_BY_STAND.PROP_ID</code>.
     */
    public final TableField<DictKafkaPropValueByStandRecord, Object> PROP_ID = createField(DSL.name("PROP_ID"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.DICT_KAFKA_PROP_VALUE_BY_STAND.STAND_ID</code>.
     */
    public final TableField<DictKafkaPropValueByStandRecord, Object> STAND_ID = createField(DSL.name("STAND_ID"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.DICT_KAFKA_PROP_VALUE_BY_STAND.PROP_VALUE</code>.
     */
    public final TableField<DictKafkaPropValueByStandRecord, Object> PROP_VALUE = createField(DSL.name("PROP_VALUE"), SQLDataType.OTHER, this, "");

    private DictKafkaPropValueByStand(Name alias, Table<DictKafkaPropValueByStandRecord> aliased) {
        this(alias, aliased, null);
    }

    private DictKafkaPropValueByStand(Name alias, Table<DictKafkaPropValueByStandRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>LOCALDEV.DICT_KAFKA_PROP_VALUE_BY_STAND</code> table reference
     */
    public DictKafkaPropValueByStand(String alias) {
        this(DSL.name(alias), DICT_KAFKA_PROP_VALUE_BY_STAND);
    }

    /**
     * Create an aliased <code>LOCALDEV.DICT_KAFKA_PROP_VALUE_BY_STAND</code> table reference
     */
    public DictKafkaPropValueByStand(Name alias) {
        this(alias, DICT_KAFKA_PROP_VALUE_BY_STAND);
    }

    /**
     * Create a <code>LOCALDEV.DICT_KAFKA_PROP_VALUE_BY_STAND</code> table reference
     */
    public DictKafkaPropValueByStand() {
        this(DSL.name("DICT_KAFKA_PROP_VALUE_BY_STAND"), null);
    }

    public <O extends Record> DictKafkaPropValueByStand(Table<O> child, ForeignKey<O, DictKafkaPropValueByStandRecord> key) {
        super(child, key, DICT_KAFKA_PROP_VALUE_BY_STAND);
    }

    @Override
    public Schema getSchema() {
        return Localdev.LOCALDEV;
    }

    @Override
    public UniqueKey<DictKafkaPropValueByStandRecord> getPrimaryKey() {
        return Keys.PK_DICT_KAFKA_PROP_VALUE_BY_STAND;
    }

    @Override
    public List<UniqueKey<DictKafkaPropValueByStandRecord>> getKeys() {
        return Arrays.<UniqueKey<DictKafkaPropValueByStandRecord>>asList(Keys.PK_DICT_KAFKA_PROP_VALUE_BY_STAND);
    }

    @Override
    public DictKafkaPropValueByStand as(String alias) {
        return new DictKafkaPropValueByStand(DSL.name(alias), this);
    }

    @Override
    public DictKafkaPropValueByStand as(Name alias) {
        return new DictKafkaPropValueByStand(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DictKafkaPropValueByStand rename(String name) {
        return new DictKafkaPropValueByStand(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DictKafkaPropValueByStand rename(Name name) {
        return new DictKafkaPropValueByStand(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Object, Object, Object, Object, Object> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
