/*
 * This file is generated by jOOQ.
 */
package com.baeldung.jooq.introduction.db.tables;


import com.baeldung.jooq.introduction.db.Localdev;
import com.baeldung.jooq.introduction.db.tables.records.FlinkPropertyByStandRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FlinkPropertyByStand extends TableImpl<FlinkPropertyByStandRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>LOCALDEV.FLINK_PROPERTY_BY_STAND</code>
     */
    public static final FlinkPropertyByStand FLINK_PROPERTY_BY_STAND = new FlinkPropertyByStand();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FlinkPropertyByStandRecord> getRecordType() {
        return FlinkPropertyByStandRecord.class;
    }

    /**
     * The column <code>LOCALDEV.FLINK_PROPERTY_BY_STAND.SERVICE_ID</code>.
     */
    public final TableField<FlinkPropertyByStandRecord, Object> SERVICE_ID = createField(DSL.name("SERVICE_ID"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.FLINK_PROPERTY_BY_STAND.PROFILE_ID</code>.
     */
    public final TableField<FlinkPropertyByStandRecord, Object> PROFILE_ID = createField(DSL.name("PROFILE_ID"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.FLINK_PROPERTY_BY_STAND.STAND</code>.
     */
    public final TableField<FlinkPropertyByStandRecord, Object> STAND = createField(DSL.name("STAND"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.FLINK_PROPERTY_BY_STAND.PROP_ID</code>.
     */
    public final TableField<FlinkPropertyByStandRecord, Object> PROP_ID = createField(DSL.name("PROP_ID"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.FLINK_PROPERTY_BY_STAND.PROP_VALUE</code>.
     */
    public final TableField<FlinkPropertyByStandRecord, Object> PROP_VALUE = createField(DSL.name("PROP_VALUE"), SQLDataType.OTHER, this, "");

    private FlinkPropertyByStand(Name alias, Table<FlinkPropertyByStandRecord> aliased) {
        this(alias, aliased, null);
    }

    private FlinkPropertyByStand(Name alias, Table<FlinkPropertyByStandRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view());
    }

    /**
     * Create an aliased <code>LOCALDEV.FLINK_PROPERTY_BY_STAND</code> table reference
     */
    public FlinkPropertyByStand(String alias) {
        this(DSL.name(alias), FLINK_PROPERTY_BY_STAND);
    }

    /**
     * Create an aliased <code>LOCALDEV.FLINK_PROPERTY_BY_STAND</code> table reference
     */
    public FlinkPropertyByStand(Name alias) {
        this(alias, FLINK_PROPERTY_BY_STAND);
    }

    /**
     * Create a <code>LOCALDEV.FLINK_PROPERTY_BY_STAND</code> table reference
     */
    public FlinkPropertyByStand() {
        this(DSL.name("FLINK_PROPERTY_BY_STAND"), null);
    }

    public <O extends Record> FlinkPropertyByStand(Table<O> child, ForeignKey<O, FlinkPropertyByStandRecord> key) {
        super(child, key, FLINK_PROPERTY_BY_STAND);
    }

    @Override
    public Schema getSchema() {
        return Localdev.LOCALDEV;
    }

    @Override
    public FlinkPropertyByStand as(String alias) {
        return new FlinkPropertyByStand(DSL.name(alias), this);
    }

    @Override
    public FlinkPropertyByStand as(Name alias) {
        return new FlinkPropertyByStand(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public FlinkPropertyByStand rename(String name) {
        return new FlinkPropertyByStand(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FlinkPropertyByStand rename(Name name) {
        return new FlinkPropertyByStand(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Object, Object, Object, Object, Object> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
