/*
 * This file is generated by jOOQ.
 */
package com.baeldung.jooq.introduction.db.tables;


import com.baeldung.jooq.introduction.db.Localdev;
import com.baeldung.jooq.introduction.db.tables.records.FullFlinkServicePropertyStandRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FullFlinkServicePropertyStand extends TableImpl<FullFlinkServicePropertyStandRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>LOCALDEV.FULL_FLINK_SERVICE_PROPERTY_STAND</code>
     */
    public static final FullFlinkServicePropertyStand FULL_FLINK_SERVICE_PROPERTY_STAND = new FullFlinkServicePropertyStand();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FullFlinkServicePropertyStandRecord> getRecordType() {
        return FullFlinkServicePropertyStandRecord.class;
    }

    /**
     * The column <code>LOCALDEV.FULL_FLINK_SERVICE_PROPERTY_STAND.PRIORITY</code>.
     */
    public final TableField<FullFlinkServicePropertyStandRecord, Object> PRIORITY = createField(DSL.name("PRIORITY"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.FULL_FLINK_SERVICE_PROPERTY_STAND.SERVICE_ID</code>.
     */
    public final TableField<FullFlinkServicePropertyStandRecord, Object> SERVICE_ID = createField(DSL.name("SERVICE_ID"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.FULL_FLINK_SERVICE_PROPERTY_STAND.PROFILE_ID</code>.
     */
    public final TableField<FullFlinkServicePropertyStandRecord, Object> PROFILE_ID = createField(DSL.name("PROFILE_ID"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.FULL_FLINK_SERVICE_PROPERTY_STAND.STAND</code>.
     */
    public final TableField<FullFlinkServicePropertyStandRecord, Object> STAND = createField(DSL.name("STAND"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.FULL_FLINK_SERVICE_PROPERTY_STAND.PROP_ID</code>.
     */
    public final TableField<FullFlinkServicePropertyStandRecord, Object> PROP_ID = createField(DSL.name("PROP_ID"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.FULL_FLINK_SERVICE_PROPERTY_STAND.PROP_VALUE</code>.
     */
    public final TableField<FullFlinkServicePropertyStandRecord, Object> PROP_VALUE = createField(DSL.name("PROP_VALUE"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.FULL_FLINK_SERVICE_PROPERTY_STAND.TYPE_PROPERTY</code>.
     */
    public final TableField<FullFlinkServicePropertyStandRecord, Object> TYPE_PROPERTY = createField(DSL.name("TYPE_PROPERTY"), SQLDataType.OTHER, this, "");

    private FullFlinkServicePropertyStand(Name alias, Table<FullFlinkServicePropertyStandRecord> aliased) {
        this(alias, aliased, null);
    }

    private FullFlinkServicePropertyStand(Name alias, Table<FullFlinkServicePropertyStandRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view());
    }

    /**
     * Create an aliased <code>LOCALDEV.FULL_FLINK_SERVICE_PROPERTY_STAND</code> table reference
     */
    public FullFlinkServicePropertyStand(String alias) {
        this(DSL.name(alias), FULL_FLINK_SERVICE_PROPERTY_STAND);
    }

    /**
     * Create an aliased <code>LOCALDEV.FULL_FLINK_SERVICE_PROPERTY_STAND</code> table reference
     */
    public FullFlinkServicePropertyStand(Name alias) {
        this(alias, FULL_FLINK_SERVICE_PROPERTY_STAND);
    }

    /**
     * Create a <code>LOCALDEV.FULL_FLINK_SERVICE_PROPERTY_STAND</code> table reference
     */
    public FullFlinkServicePropertyStand() {
        this(DSL.name("FULL_FLINK_SERVICE_PROPERTY_STAND"), null);
    }

    public <O extends Record> FullFlinkServicePropertyStand(Table<O> child, ForeignKey<O, FullFlinkServicePropertyStandRecord> key) {
        super(child, key, FULL_FLINK_SERVICE_PROPERTY_STAND);
    }

    @Override
    public Schema getSchema() {
        return Localdev.LOCALDEV;
    }

    @Override
    public FullFlinkServicePropertyStand as(String alias) {
        return new FullFlinkServicePropertyStand(DSL.name(alias), this);
    }

    @Override
    public FullFlinkServicePropertyStand as(Name alias) {
        return new FullFlinkServicePropertyStand(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public FullFlinkServicePropertyStand rename(String name) {
        return new FullFlinkServicePropertyStand(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FullFlinkServicePropertyStand rename(Name name) {
        return new FullFlinkServicePropertyStand(name, null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<Object, Object, Object, Object, Object, Object, Object> fieldsRow() {
        return (Row7) super.fieldsRow();
    }
}
