/*
 * This file is generated by jOOQ.
 */
package com.baeldung.jooq.introduction.db.tables;


import com.baeldung.jooq.introduction.db.Keys;
import com.baeldung.jooq.introduction.db.Localdev;
import com.baeldung.jooq.introduction.db.tables.records.MetaPropertyFunctionRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MetaPropertyFunction extends TableImpl<MetaPropertyFunctionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>LOCALDEV.META_PROPERTY_FUNCTION</code>
     */
    public static final MetaPropertyFunction META_PROPERTY_FUNCTION = new MetaPropertyFunction();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MetaPropertyFunctionRecord> getRecordType() {
        return MetaPropertyFunctionRecord.class;
    }

    /**
     * The column <code>LOCALDEV.META_PROPERTY_FUNCTION.ID</code>.
     */
    public final TableField<MetaPropertyFunctionRecord, Object> ID = createField(DSL.name("ID"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.META_PROPERTY_FUNCTION.DESCRIPTION</code>.
     */
    public final TableField<MetaPropertyFunctionRecord, Object> DESCRIPTION = createField(DSL.name("DESCRIPTION"), SQLDataType.OTHER, this, "");

    private MetaPropertyFunction(Name alias, Table<MetaPropertyFunctionRecord> aliased) {
        this(alias, aliased, null);
    }

    private MetaPropertyFunction(Name alias, Table<MetaPropertyFunctionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>LOCALDEV.META_PROPERTY_FUNCTION</code> table reference
     */
    public MetaPropertyFunction(String alias) {
        this(DSL.name(alias), META_PROPERTY_FUNCTION);
    }

    /**
     * Create an aliased <code>LOCALDEV.META_PROPERTY_FUNCTION</code> table reference
     */
    public MetaPropertyFunction(Name alias) {
        this(alias, META_PROPERTY_FUNCTION);
    }

    /**
     * Create a <code>LOCALDEV.META_PROPERTY_FUNCTION</code> table reference
     */
    public MetaPropertyFunction() {
        this(DSL.name("META_PROPERTY_FUNCTION"), null);
    }

    public <O extends Record> MetaPropertyFunction(Table<O> child, ForeignKey<O, MetaPropertyFunctionRecord> key) {
        super(child, key, META_PROPERTY_FUNCTION);
    }

    @Override
    public Schema getSchema() {
        return Localdev.LOCALDEV;
    }

    @Override
    public UniqueKey<MetaPropertyFunctionRecord> getPrimaryKey() {
        return Keys.PK_META_PROPERTY_FUNCTION;
    }

    @Override
    public List<UniqueKey<MetaPropertyFunctionRecord>> getKeys() {
        return Arrays.<UniqueKey<MetaPropertyFunctionRecord>>asList(Keys.PK_META_PROPERTY_FUNCTION);
    }

    @Override
    public MetaPropertyFunction as(String alias) {
        return new MetaPropertyFunction(DSL.name(alias), this);
    }

    @Override
    public MetaPropertyFunction as(Name alias) {
        return new MetaPropertyFunction(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public MetaPropertyFunction rename(String name) {
        return new MetaPropertyFunction(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MetaPropertyFunction rename(Name name) {
        return new MetaPropertyFunction(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Object, Object> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
