/*
 * This file is generated by jOOQ.
 */
package com.baeldung.jooq.introduction.db.tables;


import com.baeldung.jooq.introduction.db.Localdev;
import com.baeldung.jooq.introduction.db.tables.records.RepTopicNameByStandRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RepTopicNameByStand extends TableImpl<RepTopicNameByStandRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>LOCALDEV.REP_TOPIC_NAME_BY_STAND</code>
     */
    public static final RepTopicNameByStand REP_TOPIC_NAME_BY_STAND = new RepTopicNameByStand();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RepTopicNameByStandRecord> getRecordType() {
        return RepTopicNameByStandRecord.class;
    }

    /**
     * The column <code>LOCALDEV.REP_TOPIC_NAME_BY_STAND.TOPIC_ID</code>.
     */
    public final TableField<RepTopicNameByStandRecord, Object> TOPIC_ID = createField(DSL.name("TOPIC_ID"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.REP_TOPIC_NAME_BY_STAND.TOPIC_NAME</code>.
     */
    public final TableField<RepTopicNameByStandRecord, Object> TOPIC_NAME = createField(DSL.name("TOPIC_NAME"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.REP_TOPIC_NAME_BY_STAND.STAND</code>.
     */
    public final TableField<RepTopicNameByStandRecord, Object> STAND = createField(DSL.name("STAND"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.REP_TOPIC_NAME_BY_STAND.USED</code>.
     */
    public final TableField<RepTopicNameByStandRecord, Object> USED = createField(DSL.name("USED"), SQLDataType.OTHER, this, "");

    private RepTopicNameByStand(Name alias, Table<RepTopicNameByStandRecord> aliased) {
        this(alias, aliased, null);
    }

    private RepTopicNameByStand(Name alias, Table<RepTopicNameByStandRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view());
    }

    /**
     * Create an aliased <code>LOCALDEV.REP_TOPIC_NAME_BY_STAND</code> table reference
     */
    public RepTopicNameByStand(String alias) {
        this(DSL.name(alias), REP_TOPIC_NAME_BY_STAND);
    }

    /**
     * Create an aliased <code>LOCALDEV.REP_TOPIC_NAME_BY_STAND</code> table reference
     */
    public RepTopicNameByStand(Name alias) {
        this(alias, REP_TOPIC_NAME_BY_STAND);
    }

    /**
     * Create a <code>LOCALDEV.REP_TOPIC_NAME_BY_STAND</code> table reference
     */
    public RepTopicNameByStand() {
        this(DSL.name("REP_TOPIC_NAME_BY_STAND"), null);
    }

    public <O extends Record> RepTopicNameByStand(Table<O> child, ForeignKey<O, RepTopicNameByStandRecord> key) {
        super(child, key, REP_TOPIC_NAME_BY_STAND);
    }

    @Override
    public Schema getSchema() {
        return Localdev.LOCALDEV;
    }

    @Override
    public RepTopicNameByStand as(String alias) {
        return new RepTopicNameByStand(DSL.name(alias), this);
    }

    @Override
    public RepTopicNameByStand as(Name alias) {
        return new RepTopicNameByStand(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RepTopicNameByStand rename(String name) {
        return new RepTopicNameByStand(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RepTopicNameByStand rename(Name name) {
        return new RepTopicNameByStand(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Object, Object, Object, Object> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
