/*
 * This file is generated by jOOQ.
 */
package com.baeldung.jooq.introduction.db.tables;


import com.baeldung.jooq.introduction.db.Localdev;
import com.baeldung.jooq.introduction.db.tables.records.ServiceTopicNameByStandRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ServiceTopicNameByStand extends TableImpl<ServiceTopicNameByStandRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>LOCALDEV.SERVICE_TOPIC_NAME_BY_STAND</code>
     */
    public static final ServiceTopicNameByStand SERVICE_TOPIC_NAME_BY_STAND = new ServiceTopicNameByStand();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ServiceTopicNameByStandRecord> getRecordType() {
        return ServiceTopicNameByStandRecord.class;
    }

    /**
     * The column <code>LOCALDEV.SERVICE_TOPIC_NAME_BY_STAND.GRAPH_ID</code>.
     */
    public final TableField<ServiceTopicNameByStandRecord, Object> GRAPH_ID = createField(DSL.name("GRAPH_ID"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.SERVICE_TOPIC_NAME_BY_STAND.SERVICE_ID</code>.
     */
    public final TableField<ServiceTopicNameByStandRecord, Object> SERVICE_ID = createField(DSL.name("SERVICE_ID"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.SERVICE_TOPIC_NAME_BY_STAND.PROFILE_ID</code>.
     */
    public final TableField<ServiceTopicNameByStandRecord, Object> PROFILE_ID = createField(DSL.name("PROFILE_ID"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.SERVICE_TOPIC_NAME_BY_STAND.STAND</code>.
     */
    public final TableField<ServiceTopicNameByStandRecord, Object> STAND = createField(DSL.name("STAND"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.SERVICE_TOPIC_NAME_BY_STAND.PROP_ID</code>.
     */
    public final TableField<ServiceTopicNameByStandRecord, Object> PROP_ID = createField(DSL.name("PROP_ID"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>LOCALDEV.SERVICE_TOPIC_NAME_BY_STAND.PROP_VALUE</code>.
     */
    public final TableField<ServiceTopicNameByStandRecord, Object> PROP_VALUE = createField(DSL.name("PROP_VALUE"), SQLDataType.OTHER, this, "");

    private ServiceTopicNameByStand(Name alias, Table<ServiceTopicNameByStandRecord> aliased) {
        this(alias, aliased, null);
    }

    private ServiceTopicNameByStand(Name alias, Table<ServiceTopicNameByStandRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view());
    }

    /**
     * Create an aliased <code>LOCALDEV.SERVICE_TOPIC_NAME_BY_STAND</code> table reference
     */
    public ServiceTopicNameByStand(String alias) {
        this(DSL.name(alias), SERVICE_TOPIC_NAME_BY_STAND);
    }

    /**
     * Create an aliased <code>LOCALDEV.SERVICE_TOPIC_NAME_BY_STAND</code> table reference
     */
    public ServiceTopicNameByStand(Name alias) {
        this(alias, SERVICE_TOPIC_NAME_BY_STAND);
    }

    /**
     * Create a <code>LOCALDEV.SERVICE_TOPIC_NAME_BY_STAND</code> table reference
     */
    public ServiceTopicNameByStand() {
        this(DSL.name("SERVICE_TOPIC_NAME_BY_STAND"), null);
    }

    public <O extends Record> ServiceTopicNameByStand(Table<O> child, ForeignKey<O, ServiceTopicNameByStandRecord> key) {
        super(child, key, SERVICE_TOPIC_NAME_BY_STAND);
    }

    @Override
    public Schema getSchema() {
        return Localdev.LOCALDEV;
    }

    @Override
    public ServiceTopicNameByStand as(String alias) {
        return new ServiceTopicNameByStand(DSL.name(alias), this);
    }

    @Override
    public ServiceTopicNameByStand as(Name alias) {
        return new ServiceTopicNameByStand(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ServiceTopicNameByStand rename(String name) {
        return new ServiceTopicNameByStand(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ServiceTopicNameByStand rename(Name name) {
        return new ServiceTopicNameByStand(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Object, Object, Object, Object, Object, Object> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
