/*
 * This file is generated by jOOQ.
 */
package com.baeldung.jooq.introduction.db;


import com.baeldung.jooq.introduction.db.tables.AllPlaceholder;
import com.baeldung.jooq.introduction.db.tables.CkEnvPropUnique;
import com.baeldung.jooq.introduction.db.tables.Databasechangelog;
import com.baeldung.jooq.introduction.db.tables.Databasechangeloglock;
import com.baeldung.jooq.introduction.db.tables.DictAbstractGraphNode;
import com.baeldung.jooq.introduction.db.tables.DictArrow;
import com.baeldung.jooq.introduction.db.tables.DictFlinkPropValue;
import com.baeldung.jooq.introduction.db.tables.DictKafkaProp;
import com.baeldung.jooq.introduction.db.tables.DictKafkaPropValue;
import com.baeldung.jooq.introduction.db.tables.DictKafkaPropValueByStand;
import com.baeldung.jooq.introduction.db.tables.DictKafkaPropertyGrp;
import com.baeldung.jooq.introduction.db.tables.DictPlaceHolder;
import com.baeldung.jooq.introduction.db.tables.DictPlaceHolderByService;
import com.baeldung.jooq.introduction.db.tables.DictService;
import com.baeldung.jooq.introduction.db.tables.DictServiceIns;
import com.baeldung.jooq.introduction.db.tables.DictServiceNode;
import com.baeldung.jooq.introduction.db.tables.DictServiceProfile;
import com.baeldung.jooq.introduction.db.tables.DictTopicIns;
import com.baeldung.jooq.introduction.db.tables.DictTopicNode;
import com.baeldung.jooq.introduction.db.tables.DictTopicParamsByStand;
import com.baeldung.jooq.introduction.db.tables.FlinkPropertyByStand;
import com.baeldung.jooq.introduction.db.tables.FullFlinkServicePropertyStand;
import com.baeldung.jooq.introduction.db.tables.KafkaPropValueByStand;
import com.baeldung.jooq.introduction.db.tables.KafkaPropertyBySevice;
import com.baeldung.jooq.introduction.db.tables.KafkaTopicByService;
import com.baeldung.jooq.introduction.db.tables.MetaPropertyFunction;
import com.baeldung.jooq.introduction.db.tables.MetaStand;
import com.baeldung.jooq.introduction.db.tables.RepTopicNameByStand;
import com.baeldung.jooq.introduction.db.tables.RepTopicUse;
import com.baeldung.jooq.introduction.db.tables.ResolvablePlaceholder;
import com.baeldung.jooq.introduction.db.tables.ServiceTopicNameByStand;


/**
 * Convenience access to all tables in LOCALDEV.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>LOCALDEV.ALL_PLACEHOLDER</code>.
     */
    public static final AllPlaceholder ALL_PLACEHOLDER = AllPlaceholder.ALL_PLACEHOLDER;

    /**
     * The table <code>LOCALDEV.CK_ENV_PROP_UNIQUE</code>.
     */
    public static final CkEnvPropUnique CK_ENV_PROP_UNIQUE = CkEnvPropUnique.CK_ENV_PROP_UNIQUE;

    /**
     * The table <code>LOCALDEV.DATABASECHANGELOG</code>.
     */
    public static final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>LOCALDEV.DATABASECHANGELOGLOCK</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>LOCALDEV.DICT_ABSTRACT_GRAPH_NODE</code>.
     */
    public static final DictAbstractGraphNode DICT_ABSTRACT_GRAPH_NODE = DictAbstractGraphNode.DICT_ABSTRACT_GRAPH_NODE;

    /**
     * The table <code>LOCALDEV.DICT_ARROW</code>.
     */
    public static final DictArrow DICT_ARROW = DictArrow.DICT_ARROW;

    /**
     * The table <code>LOCALDEV.DICT_FLINK_PROP_VALUE</code>.
     */
    public static final DictFlinkPropValue DICT_FLINK_PROP_VALUE = DictFlinkPropValue.DICT_FLINK_PROP_VALUE;

    /**
     * The table <code>LOCALDEV.DICT_KAFKA_PROP</code>.
     */
    public static final DictKafkaProp DICT_KAFKA_PROP = DictKafkaProp.DICT_KAFKA_PROP;

    /**
     * The table <code>LOCALDEV.DICT_KAFKA_PROP_VALUE</code>.
     */
    public static final DictKafkaPropValue DICT_KAFKA_PROP_VALUE = DictKafkaPropValue.DICT_KAFKA_PROP_VALUE;

    /**
     * The table <code>LOCALDEV.DICT_KAFKA_PROP_VALUE_BY_STAND</code>.
     */
    public static final DictKafkaPropValueByStand DICT_KAFKA_PROP_VALUE_BY_STAND = DictKafkaPropValueByStand.DICT_KAFKA_PROP_VALUE_BY_STAND;

    /**
     * The table <code>LOCALDEV.DICT_KAFKA_PROPERTY_GRP</code>.
     */
    public static final DictKafkaPropertyGrp DICT_KAFKA_PROPERTY_GRP = DictKafkaPropertyGrp.DICT_KAFKA_PROPERTY_GRP;

    /**
     * The table <code>LOCALDEV.DICT_PLACE_HOLDER</code>.
     */
    public static final DictPlaceHolder DICT_PLACE_HOLDER = DictPlaceHolder.DICT_PLACE_HOLDER;

    /**
     * The table <code>LOCALDEV.DICT_PLACE_HOLDER_BY_SERVICE</code>.
     */
    public static final DictPlaceHolderByService DICT_PLACE_HOLDER_BY_SERVICE = DictPlaceHolderByService.DICT_PLACE_HOLDER_BY_SERVICE;

    /**
     * The table <code>LOCALDEV.DICT_SERVICE</code>.
     */
    public static final DictService DICT_SERVICE = DictService.DICT_SERVICE;

    /**
     * The table <code>LOCALDEV.DICT_SERVICE_INS</code>.
     */
    public static final DictServiceIns DICT_SERVICE_INS = DictServiceIns.DICT_SERVICE_INS;

    /**
     * The table <code>LOCALDEV.DICT_SERVICE_NODE</code>.
     */
    public static final DictServiceNode DICT_SERVICE_NODE = DictServiceNode.DICT_SERVICE_NODE;

    /**
     * The table <code>LOCALDEV.DICT_SERVICE_PROFILE</code>.
     */
    public static final DictServiceProfile DICT_SERVICE_PROFILE = DictServiceProfile.DICT_SERVICE_PROFILE;

    /**
     * The table <code>LOCALDEV.DICT_TOPIC_INS</code>.
     */
    public static final DictTopicIns DICT_TOPIC_INS = DictTopicIns.DICT_TOPIC_INS;

    /**
     * The table <code>LOCALDEV.DICT_TOPIC_NODE</code>.
     */
    public static final DictTopicNode DICT_TOPIC_NODE = DictTopicNode.DICT_TOPIC_NODE;

    /**
     * The table <code>LOCALDEV.DICT_TOPIC_PARAMS_BY_STAND</code>.
     */
    public static final DictTopicParamsByStand DICT_TOPIC_PARAMS_BY_STAND = DictTopicParamsByStand.DICT_TOPIC_PARAMS_BY_STAND;

    /**
     * The table <code>LOCALDEV.FLINK_PROPERTY_BY_STAND</code>.
     */
    public static final FlinkPropertyByStand FLINK_PROPERTY_BY_STAND = FlinkPropertyByStand.FLINK_PROPERTY_BY_STAND;

    /**
     * The table <code>LOCALDEV.FULL_FLINK_SERVICE_PROPERTY_STAND</code>.
     */
    public static final FullFlinkServicePropertyStand FULL_FLINK_SERVICE_PROPERTY_STAND = FullFlinkServicePropertyStand.FULL_FLINK_SERVICE_PROPERTY_STAND;

    /**
     * The table <code>LOCALDEV.KAFKA_PROP_VALUE_BY_STAND</code>.
     */
    public static final KafkaPropValueByStand KAFKA_PROP_VALUE_BY_STAND = KafkaPropValueByStand.KAFKA_PROP_VALUE_BY_STAND;

    /**
     * The table <code>LOCALDEV.KAFKA_PROPERTY_BY_SEVICE</code>.
     */
    public static final KafkaPropertyBySevice KAFKA_PROPERTY_BY_SEVICE = KafkaPropertyBySevice.KAFKA_PROPERTY_BY_SEVICE;

    /**
     * The table <code>LOCALDEV.KAFKA_TOPIC_BY_SERVICE</code>.
     */
    public static final KafkaTopicByService KAFKA_TOPIC_BY_SERVICE = KafkaTopicByService.KAFKA_TOPIC_BY_SERVICE;

    /**
     * The table <code>LOCALDEV.META_PROPERTY_FUNCTION</code>.
     */
    public static final MetaPropertyFunction META_PROPERTY_FUNCTION = MetaPropertyFunction.META_PROPERTY_FUNCTION;

    /**
     * The table <code>LOCALDEV.META_STAND</code>.
     */
    public static final MetaStand META_STAND = MetaStand.META_STAND;

    /**
     * The table <code>LOCALDEV.REP_TOPIC_NAME_BY_STAND</code>.
     */
    public static final RepTopicNameByStand REP_TOPIC_NAME_BY_STAND = RepTopicNameByStand.REP_TOPIC_NAME_BY_STAND;

    /**
     * The table <code>LOCALDEV.REP_TOPIC_USE</code>.
     */
    public static final RepTopicUse REP_TOPIC_USE = RepTopicUse.REP_TOPIC_USE;

    /**
     * The table <code>LOCALDEV.RESOLVABLE_PLACEHOLDER</code>.
     */
    public static final ResolvablePlaceholder RESOLVABLE_PLACEHOLDER = ResolvablePlaceholder.RESOLVABLE_PLACEHOLDER;

    /**
     * The table <code>LOCALDEV.SERVICE_TOPIC_NAME_BY_STAND</code>.
     */
    public static final ServiceTopicNameByStand SERVICE_TOPIC_NAME_BY_STAND = ServiceTopicNameByStand.SERVICE_TOPIC_NAME_BY_STAND;
}
