/*
 * This file is generated by jOOQ.
 */
package com.baeldung.jooq.introduction.db.tables.records;


import com.baeldung.jooq.introduction.db.tables.AllPlaceholder;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AllPlaceholderRecord extends TableRecordImpl<AllPlaceholderRecord> implements Record4<Object, Object, Object, Object> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>LOCALDEV.ALL_PLACEHOLDER.SERVICE_ID</code>.
     */
    public AllPlaceholderRecord setServiceId(Object value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.ALL_PLACEHOLDER.SERVICE_ID</code>.
     */
    public Object getServiceId() {
        return get(0);
    }

    /**
     * Setter for <code>LOCALDEV.ALL_PLACEHOLDER.PROFILE_ID</code>.
     */
    public AllPlaceholderRecord setProfileId(Object value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.ALL_PLACEHOLDER.PROFILE_ID</code>.
     */
    public Object getProfileId() {
        return get(1);
    }

    /**
     * Setter for <code>LOCALDEV.ALL_PLACEHOLDER.STAND</code>.
     */
    public AllPlaceholderRecord setStand(Object value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.ALL_PLACEHOLDER.STAND</code>.
     */
    public Object getStand() {
        return get(2);
    }

    /**
     * Setter for <code>LOCALDEV.ALL_PLACEHOLDER.PROP_VALUE</code>.
     */
    public AllPlaceholderRecord setPropValue(Object value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.ALL_PLACEHOLDER.PROP_VALUE</code>.
     */
    public Object getPropValue() {
        return get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Object, Object, Object, Object> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Object, Object, Object, Object> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Object> field1() {
        return AllPlaceholder.ALL_PLACEHOLDER.SERVICE_ID;
    }

    @Override
    public Field<Object> field2() {
        return AllPlaceholder.ALL_PLACEHOLDER.PROFILE_ID;
    }

    @Override
    public Field<Object> field3() {
        return AllPlaceholder.ALL_PLACEHOLDER.STAND;
    }

    @Override
    public Field<Object> field4() {
        return AllPlaceholder.ALL_PLACEHOLDER.PROP_VALUE;
    }

    @Override
    public Object component1() {
        return getServiceId();
    }

    @Override
    public Object component2() {
        return getProfileId();
    }

    @Override
    public Object component3() {
        return getStand();
    }

    @Override
    public Object component4() {
        return getPropValue();
    }

    @Override
    public Object value1() {
        return getServiceId();
    }

    @Override
    public Object value2() {
        return getProfileId();
    }

    @Override
    public Object value3() {
        return getStand();
    }

    @Override
    public Object value4() {
        return getPropValue();
    }

    @Override
    public AllPlaceholderRecord value1(Object value) {
        setServiceId(value);
        return this;
    }

    @Override
    public AllPlaceholderRecord value2(Object value) {
        setProfileId(value);
        return this;
    }

    @Override
    public AllPlaceholderRecord value3(Object value) {
        setStand(value);
        return this;
    }

    @Override
    public AllPlaceholderRecord value4(Object value) {
        setPropValue(value);
        return this;
    }

    @Override
    public AllPlaceholderRecord values(Object value1, Object value2, Object value3, Object value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AllPlaceholderRecord
     */
    public AllPlaceholderRecord() {
        super(AllPlaceholder.ALL_PLACEHOLDER);
    }

    /**
     * Create a detached, initialised AllPlaceholderRecord
     */
    public AllPlaceholderRecord(Object serviceId, Object profileId, Object stand, Object propValue) {
        super(AllPlaceholder.ALL_PLACEHOLDER);

        setServiceId(serviceId);
        setProfileId(profileId);
        setStand(stand);
        setPropValue(propValue);
    }
}
