/*
 * This file is generated by jOOQ.
 */
package com.baeldung.jooq.introduction.db.tables.records;


import com.baeldung.jooq.introduction.db.tables.CkEnvPropUnique;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CkEnvPropUniqueRecord extends TableRecordImpl<CkEnvPropUniqueRecord> implements Record5<Object, Object, Object, Object, Object> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>LOCALDEV.CK_ENV_PROP_UNIQUE.SERVICE_ID</code>.
     */
    public CkEnvPropUniqueRecord setServiceId(Object value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.CK_ENV_PROP_UNIQUE.SERVICE_ID</code>.
     */
    public Object getServiceId() {
        return get(0);
    }

    /**
     * Setter for <code>LOCALDEV.CK_ENV_PROP_UNIQUE.PROFILE_ID</code>.
     */
    public CkEnvPropUniqueRecord setProfileId(Object value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.CK_ENV_PROP_UNIQUE.PROFILE_ID</code>.
     */
    public Object getProfileId() {
        return get(1);
    }

    /**
     * Setter for <code>LOCALDEV.CK_ENV_PROP_UNIQUE.PROP_ID</code>.
     */
    public CkEnvPropUniqueRecord setPropId(Object value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.CK_ENV_PROP_UNIQUE.PROP_ID</code>.
     */
    public Object getPropId() {
        return get(2);
    }

    /**
     * Setter for <code>LOCALDEV.CK_ENV_PROP_UNIQUE.TYPE_PROPERTY</code>.
     */
    public CkEnvPropUniqueRecord setTypeProperty(Object value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.CK_ENV_PROP_UNIQUE.TYPE_PROPERTY</code>.
     */
    public Object getTypeProperty() {
        return get(3);
    }

    /**
     * Setter for <code>LOCALDEV.CK_ENV_PROP_UNIQUE.STAND</code>.
     */
    public CkEnvPropUniqueRecord setStand(Object value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.CK_ENV_PROP_UNIQUE.STAND</code>.
     */
    public Object getStand() {
        return get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Object, Object, Object, Object, Object> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Object, Object, Object, Object, Object> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Object> field1() {
        return CkEnvPropUnique.CK_ENV_PROP_UNIQUE.SERVICE_ID;
    }

    @Override
    public Field<Object> field2() {
        return CkEnvPropUnique.CK_ENV_PROP_UNIQUE.PROFILE_ID;
    }

    @Override
    public Field<Object> field3() {
        return CkEnvPropUnique.CK_ENV_PROP_UNIQUE.PROP_ID;
    }

    @Override
    public Field<Object> field4() {
        return CkEnvPropUnique.CK_ENV_PROP_UNIQUE.TYPE_PROPERTY;
    }

    @Override
    public Field<Object> field5() {
        return CkEnvPropUnique.CK_ENV_PROP_UNIQUE.STAND;
    }

    @Override
    public Object component1() {
        return getServiceId();
    }

    @Override
    public Object component2() {
        return getProfileId();
    }

    @Override
    public Object component3() {
        return getPropId();
    }

    @Override
    public Object component4() {
        return getTypeProperty();
    }

    @Override
    public Object component5() {
        return getStand();
    }

    @Override
    public Object value1() {
        return getServiceId();
    }

    @Override
    public Object value2() {
        return getProfileId();
    }

    @Override
    public Object value3() {
        return getPropId();
    }

    @Override
    public Object value4() {
        return getTypeProperty();
    }

    @Override
    public Object value5() {
        return getStand();
    }

    @Override
    public CkEnvPropUniqueRecord value1(Object value) {
        setServiceId(value);
        return this;
    }

    @Override
    public CkEnvPropUniqueRecord value2(Object value) {
        setProfileId(value);
        return this;
    }

    @Override
    public CkEnvPropUniqueRecord value3(Object value) {
        setPropId(value);
        return this;
    }

    @Override
    public CkEnvPropUniqueRecord value4(Object value) {
        setTypeProperty(value);
        return this;
    }

    @Override
    public CkEnvPropUniqueRecord value5(Object value) {
        setStand(value);
        return this;
    }

    @Override
    public CkEnvPropUniqueRecord values(Object value1, Object value2, Object value3, Object value4, Object value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CkEnvPropUniqueRecord
     */
    public CkEnvPropUniqueRecord() {
        super(CkEnvPropUnique.CK_ENV_PROP_UNIQUE);
    }

    /**
     * Create a detached, initialised CkEnvPropUniqueRecord
     */
    public CkEnvPropUniqueRecord(Object serviceId, Object profileId, Object propId, Object typeProperty, Object stand) {
        super(CkEnvPropUnique.CK_ENV_PROP_UNIQUE);

        setServiceId(serviceId);
        setProfileId(profileId);
        setPropId(propId);
        setTypeProperty(typeProperty);
        setStand(stand);
    }
}
