/*
 * This file is generated by jOOQ.
 */
package com.baeldung.jooq.introduction.db.tables.records;


import com.baeldung.jooq.introduction.db.tables.DictFlinkPropValue;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DictFlinkPropValueRecord extends UpdatableRecordImpl<DictFlinkPropValueRecord> implements Record6<Object, Object, Object, Object, Object, Object> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>LOCALDEV.DICT_FLINK_PROP_VALUE.SERVICE_ID</code>.
     */
    public DictFlinkPropValueRecord setServiceId(Object value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.DICT_FLINK_PROP_VALUE.SERVICE_ID</code>.
     */
    public Object getServiceId() {
        return get(0);
    }

    /**
     * Setter for <code>LOCALDEV.DICT_FLINK_PROP_VALUE.PROFILE_ID</code>.
     */
    public DictFlinkPropValueRecord setProfileId(Object value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.DICT_FLINK_PROP_VALUE.PROFILE_ID</code>.
     */
    public Object getProfileId() {
        return get(1);
    }

    /**
     * Setter for <code>LOCALDEV.DICT_FLINK_PROP_VALUE.PROP_ID</code>.
     */
    public DictFlinkPropValueRecord setPropId(Object value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.DICT_FLINK_PROP_VALUE.PROP_ID</code>.
     */
    public Object getPropId() {
        return get(2);
    }

    /**
     * Setter for <code>LOCALDEV.DICT_FLINK_PROP_VALUE.PROP_VALUE</code>.
     */
    public DictFlinkPropValueRecord setPropValue(Object value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.DICT_FLINK_PROP_VALUE.PROP_VALUE</code>.
     */
    public Object getPropValue() {
        return get(3);
    }

    /**
     * Setter for <code>LOCALDEV.DICT_FLINK_PROP_VALUE.IS_FUNCTION</code>.
     */
    public DictFlinkPropValueRecord setIsFunction(Object value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.DICT_FLINK_PROP_VALUE.IS_FUNCTION</code>.
     */
    public Object getIsFunction() {
        return get(4);
    }

    /**
     * Setter for <code>LOCALDEV.DICT_FLINK_PROP_VALUE.FUNCTION_ID</code>.
     */
    public DictFlinkPropValueRecord setFunctionId(Object value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.DICT_FLINK_PROP_VALUE.FUNCTION_ID</code>.
     */
    public Object getFunctionId() {
        return get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record3<Object, Object, Object> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Object, Object, Object, Object, Object, Object> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Object, Object, Object, Object, Object, Object> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Object> field1() {
        return DictFlinkPropValue.DICT_FLINK_PROP_VALUE.SERVICE_ID;
    }

    @Override
    public Field<Object> field2() {
        return DictFlinkPropValue.DICT_FLINK_PROP_VALUE.PROFILE_ID;
    }

    @Override
    public Field<Object> field3() {
        return DictFlinkPropValue.DICT_FLINK_PROP_VALUE.PROP_ID;
    }

    @Override
    public Field<Object> field4() {
        return DictFlinkPropValue.DICT_FLINK_PROP_VALUE.PROP_VALUE;
    }

    @Override
    public Field<Object> field5() {
        return DictFlinkPropValue.DICT_FLINK_PROP_VALUE.IS_FUNCTION;
    }

    @Override
    public Field<Object> field6() {
        return DictFlinkPropValue.DICT_FLINK_PROP_VALUE.FUNCTION_ID;
    }

    @Override
    public Object component1() {
        return getServiceId();
    }

    @Override
    public Object component2() {
        return getProfileId();
    }

    @Override
    public Object component3() {
        return getPropId();
    }

    @Override
    public Object component4() {
        return getPropValue();
    }

    @Override
    public Object component5() {
        return getIsFunction();
    }

    @Override
    public Object component6() {
        return getFunctionId();
    }

    @Override
    public Object value1() {
        return getServiceId();
    }

    @Override
    public Object value2() {
        return getProfileId();
    }

    @Override
    public Object value3() {
        return getPropId();
    }

    @Override
    public Object value4() {
        return getPropValue();
    }

    @Override
    public Object value5() {
        return getIsFunction();
    }

    @Override
    public Object value6() {
        return getFunctionId();
    }

    @Override
    public DictFlinkPropValueRecord value1(Object value) {
        setServiceId(value);
        return this;
    }

    @Override
    public DictFlinkPropValueRecord value2(Object value) {
        setProfileId(value);
        return this;
    }

    @Override
    public DictFlinkPropValueRecord value3(Object value) {
        setPropId(value);
        return this;
    }

    @Override
    public DictFlinkPropValueRecord value4(Object value) {
        setPropValue(value);
        return this;
    }

    @Override
    public DictFlinkPropValueRecord value5(Object value) {
        setIsFunction(value);
        return this;
    }

    @Override
    public DictFlinkPropValueRecord value6(Object value) {
        setFunctionId(value);
        return this;
    }

    @Override
    public DictFlinkPropValueRecord values(Object value1, Object value2, Object value3, Object value4, Object value5, Object value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DictFlinkPropValueRecord
     */
    public DictFlinkPropValueRecord() {
        super(DictFlinkPropValue.DICT_FLINK_PROP_VALUE);
    }

    /**
     * Create a detached, initialised DictFlinkPropValueRecord
     */
    public DictFlinkPropValueRecord(Object serviceId, Object profileId, Object propId, Object propValue, Object isFunction, Object functionId) {
        super(DictFlinkPropValue.DICT_FLINK_PROP_VALUE);

        setServiceId(serviceId);
        setProfileId(profileId);
        setPropId(propId);
        setPropValue(propValue);
        setIsFunction(isFunction);
        setFunctionId(functionId);
    }
}
