/*
 * This file is generated by jOOQ.
 */
package com.baeldung.jooq.introduction.db.tables.records;


import com.baeldung.jooq.introduction.db.tables.DictServiceIns;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DictServiceInsRecord extends TableRecordImpl<DictServiceInsRecord> implements Record4<Object, Object, Object, Object> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>LOCALDEV.DICT_SERVICE_INS.GRAPH_ID</code>.
     */
    public DictServiceInsRecord setGraphId(Object value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.DICT_SERVICE_INS.GRAPH_ID</code>.
     */
    public Object getGraphId() {
        return get(0);
    }

    /**
     * Setter for <code>LOCALDEV.DICT_SERVICE_INS.SERVICE_ID</code>.
     */
    public DictServiceInsRecord setServiceId(Object value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.DICT_SERVICE_INS.SERVICE_ID</code>.
     */
    public Object getServiceId() {
        return get(1);
    }

    /**
     * Setter for <code>LOCALDEV.DICT_SERVICE_INS.PROFILE_ID</code>.
     */
    public DictServiceInsRecord setProfileId(Object value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.DICT_SERVICE_INS.PROFILE_ID</code>.
     */
    public Object getProfileId() {
        return get(2);
    }

    /**
     * Setter for <code>LOCALDEV.DICT_SERVICE_INS.MAIN_CLASS</code>.
     */
    public DictServiceInsRecord setMainClass(Object value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.DICT_SERVICE_INS.MAIN_CLASS</code>.
     */
    public Object getMainClass() {
        return get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Object, Object, Object, Object> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Object, Object, Object, Object> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Object> field1() {
        return DictServiceIns.DICT_SERVICE_INS.GRAPH_ID;
    }

    @Override
    public Field<Object> field2() {
        return DictServiceIns.DICT_SERVICE_INS.SERVICE_ID;
    }

    @Override
    public Field<Object> field3() {
        return DictServiceIns.DICT_SERVICE_INS.PROFILE_ID;
    }

    @Override
    public Field<Object> field4() {
        return DictServiceIns.DICT_SERVICE_INS.MAIN_CLASS;
    }

    @Override
    public Object component1() {
        return getGraphId();
    }

    @Override
    public Object component2() {
        return getServiceId();
    }

    @Override
    public Object component3() {
        return getProfileId();
    }

    @Override
    public Object component4() {
        return getMainClass();
    }

    @Override
    public Object value1() {
        return getGraphId();
    }

    @Override
    public Object value2() {
        return getServiceId();
    }

    @Override
    public Object value3() {
        return getProfileId();
    }

    @Override
    public Object value4() {
        return getMainClass();
    }

    @Override
    public DictServiceInsRecord value1(Object value) {
        setGraphId(value);
        return this;
    }

    @Override
    public DictServiceInsRecord value2(Object value) {
        setServiceId(value);
        return this;
    }

    @Override
    public DictServiceInsRecord value3(Object value) {
        setProfileId(value);
        return this;
    }

    @Override
    public DictServiceInsRecord value4(Object value) {
        setMainClass(value);
        return this;
    }

    @Override
    public DictServiceInsRecord values(Object value1, Object value2, Object value3, Object value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DictServiceInsRecord
     */
    public DictServiceInsRecord() {
        super(DictServiceIns.DICT_SERVICE_INS);
    }

    /**
     * Create a detached, initialised DictServiceInsRecord
     */
    public DictServiceInsRecord(Object graphId, Object serviceId, Object profileId, Object mainClass) {
        super(DictServiceIns.DICT_SERVICE_INS);

        setGraphId(graphId);
        setServiceId(serviceId);
        setProfileId(profileId);
        setMainClass(mainClass);
    }
}
