/*
 * This file is generated by jOOQ.
 */
package com.baeldung.jooq.introduction.db.tables.records;


import com.baeldung.jooq.introduction.db.tables.DictTopicParamsByStand;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DictTopicParamsByStandRecord extends UpdatableRecordImpl<DictTopicParamsByStandRecord> implements Record4<Object, Object, Object, Object> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>LOCALDEV.DICT_TOPIC_PARAMS_BY_STAND.NODE_ID</code>.
     */
    public DictTopicParamsByStandRecord setNodeId(Object value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.DICT_TOPIC_PARAMS_BY_STAND.NODE_ID</code>.
     */
    public Object getNodeId() {
        return get(0);
    }

    /**
     * Setter for <code>LOCALDEV.DICT_TOPIC_PARAMS_BY_STAND.STAND_ID</code>.
     */
    public DictTopicParamsByStandRecord setStandId(Object value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.DICT_TOPIC_PARAMS_BY_STAND.STAND_ID</code>.
     */
    public Object getStandId() {
        return get(1);
    }

    /**
     * Setter for <code>LOCALDEV.DICT_TOPIC_PARAMS_BY_STAND.CNT_PARTITION</code>.
     */
    public DictTopicParamsByStandRecord setCntPartition(Object value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.DICT_TOPIC_PARAMS_BY_STAND.CNT_PARTITION</code>.
     */
    public Object getCntPartition() {
        return get(2);
    }

    /**
     * Setter for <code>LOCALDEV.DICT_TOPIC_PARAMS_BY_STAND.TOPIC_NAME</code>.
     */
    public DictTopicParamsByStandRecord setTopicName(Object value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.DICT_TOPIC_PARAMS_BY_STAND.TOPIC_NAME</code>.
     */
    public Object getTopicName() {
        return get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Object, Object> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Object, Object, Object, Object> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Object, Object, Object, Object> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Object> field1() {
        return DictTopicParamsByStand.DICT_TOPIC_PARAMS_BY_STAND.NODE_ID;
    }

    @Override
    public Field<Object> field2() {
        return DictTopicParamsByStand.DICT_TOPIC_PARAMS_BY_STAND.STAND_ID;
    }

    @Override
    public Field<Object> field3() {
        return DictTopicParamsByStand.DICT_TOPIC_PARAMS_BY_STAND.CNT_PARTITION;
    }

    @Override
    public Field<Object> field4() {
        return DictTopicParamsByStand.DICT_TOPIC_PARAMS_BY_STAND.TOPIC_NAME;
    }

    @Override
    public Object component1() {
        return getNodeId();
    }

    @Override
    public Object component2() {
        return getStandId();
    }

    @Override
    public Object component3() {
        return getCntPartition();
    }

    @Override
    public Object component4() {
        return getTopicName();
    }

    @Override
    public Object value1() {
        return getNodeId();
    }

    @Override
    public Object value2() {
        return getStandId();
    }

    @Override
    public Object value3() {
        return getCntPartition();
    }

    @Override
    public Object value4() {
        return getTopicName();
    }

    @Override
    public DictTopicParamsByStandRecord value1(Object value) {
        setNodeId(value);
        return this;
    }

    @Override
    public DictTopicParamsByStandRecord value2(Object value) {
        setStandId(value);
        return this;
    }

    @Override
    public DictTopicParamsByStandRecord value3(Object value) {
        setCntPartition(value);
        return this;
    }

    @Override
    public DictTopicParamsByStandRecord value4(Object value) {
        setTopicName(value);
        return this;
    }

    @Override
    public DictTopicParamsByStandRecord values(Object value1, Object value2, Object value3, Object value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DictTopicParamsByStandRecord
     */
    public DictTopicParamsByStandRecord() {
        super(DictTopicParamsByStand.DICT_TOPIC_PARAMS_BY_STAND);
    }

    /**
     * Create a detached, initialised DictTopicParamsByStandRecord
     */
    public DictTopicParamsByStandRecord(Object nodeId, Object standId, Object cntPartition, Object topicName) {
        super(DictTopicParamsByStand.DICT_TOPIC_PARAMS_BY_STAND);

        setNodeId(nodeId);
        setStandId(standId);
        setCntPartition(cntPartition);
        setTopicName(topicName);
    }
}
