/*
 * This file is generated by jOOQ.
 */
package com.baeldung.jooq.introduction.db.tables.records;


import com.baeldung.jooq.introduction.db.tables.DictPlaceHolderByService;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DictPlaceHolderByServiceRecord extends UpdatableRecordImpl<DictPlaceHolderByServiceRecord> implements Record5<Object, Object, Object, Object, Object> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>LOCALDEV.DICT_PLACE_HOLDER_BY_SERVICE.SERVICE_ID</code>.
     */
    public DictPlaceHolderByServiceRecord setServiceId(Object value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.DICT_PLACE_HOLDER_BY_SERVICE.SERVICE_ID</code>.
     */
    public Object getServiceId() {
        return get(0);
    }

    /**
     * Setter for <code>LOCALDEV.DICT_PLACE_HOLDER_BY_SERVICE.PROFILE_ID</code>.
     */
    public DictPlaceHolderByServiceRecord setProfileId(Object value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.DICT_PLACE_HOLDER_BY_SERVICE.PROFILE_ID</code>.
     */
    public Object getProfileId() {
        return get(1);
    }

    /**
     * Setter for <code>LOCALDEV.DICT_PLACE_HOLDER_BY_SERVICE.STAND_ID</code>.
     */
    public DictPlaceHolderByServiceRecord setStandId(Object value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.DICT_PLACE_HOLDER_BY_SERVICE.STAND_ID</code>.
     */
    public Object getStandId() {
        return get(2);
    }

    /**
     * Setter for <code>LOCALDEV.DICT_PLACE_HOLDER_BY_SERVICE.PLACE_HOLDER_ID</code>.
     */
    public DictPlaceHolderByServiceRecord setPlaceHolderId(Object value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.DICT_PLACE_HOLDER_BY_SERVICE.PLACE_HOLDER_ID</code>.
     */
    public Object getPlaceHolderId() {
        return get(3);
    }

    /**
     * Setter for <code>LOCALDEV.DICT_PLACE_HOLDER_BY_SERVICE.VALUE</code>.
     */
    public DictPlaceHolderByServiceRecord setValue(Object value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.DICT_PLACE_HOLDER_BY_SERVICE.VALUE</code>.
     */
    public Object getValue() {
        return get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record3<Object, Object, Object> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Object, Object, Object, Object, Object> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Object, Object, Object, Object, Object> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Object> field1() {
        return DictPlaceHolderByService.DICT_PLACE_HOLDER_BY_SERVICE.SERVICE_ID;
    }

    @Override
    public Field<Object> field2() {
        return DictPlaceHolderByService.DICT_PLACE_HOLDER_BY_SERVICE.PROFILE_ID;
    }

    @Override
    public Field<Object> field3() {
        return DictPlaceHolderByService.DICT_PLACE_HOLDER_BY_SERVICE.STAND_ID;
    }

    @Override
    public Field<Object> field4() {
        return DictPlaceHolderByService.DICT_PLACE_HOLDER_BY_SERVICE.PLACE_HOLDER_ID;
    }

    @Override
    public Field<Object> field5() {
        return DictPlaceHolderByService.DICT_PLACE_HOLDER_BY_SERVICE.VALUE;
    }

    @Override
    public Object component1() {
        return getServiceId();
    }

    @Override
    public Object component2() {
        return getProfileId();
    }

    @Override
    public Object component3() {
        return getStandId();
    }

    @Override
    public Object component4() {
        return getPlaceHolderId();
    }

    @Override
    public Object component5() {
        return getValue();
    }

    @Override
    public Object value1() {
        return getServiceId();
    }

    @Override
    public Object value2() {
        return getProfileId();
    }

    @Override
    public Object value3() {
        return getStandId();
    }

    @Override
    public Object value4() {
        return getPlaceHolderId();
    }

    @Override
    public Object value5() {
        return getValue();
    }

    @Override
    public DictPlaceHolderByServiceRecord value1(Object value) {
        setServiceId(value);
        return this;
    }

    @Override
    public DictPlaceHolderByServiceRecord value2(Object value) {
        setProfileId(value);
        return this;
    }

    @Override
    public DictPlaceHolderByServiceRecord value3(Object value) {
        setStandId(value);
        return this;
    }

    @Override
    public DictPlaceHolderByServiceRecord value4(Object value) {
        setPlaceHolderId(value);
        return this;
    }

    @Override
    public DictPlaceHolderByServiceRecord value5(Object value) {
        setValue(value);
        return this;
    }

    @Override
    public DictPlaceHolderByServiceRecord values(Object value1, Object value2, Object value3, Object value4, Object value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DictPlaceHolderByServiceRecord
     */
    public DictPlaceHolderByServiceRecord() {
        super(DictPlaceHolderByService.DICT_PLACE_HOLDER_BY_SERVICE);
    }

    /**
     * Create a detached, initialised DictPlaceHolderByServiceRecord
     */
    public DictPlaceHolderByServiceRecord(Object serviceId, Object profileId, Object standId, Object placeHolderId, Object value) {
        super(DictPlaceHolderByService.DICT_PLACE_HOLDER_BY_SERVICE);

        setServiceId(serviceId);
        setProfileId(profileId);
        setStandId(standId);
        setPlaceHolderId(placeHolderId);
        setValue(value);
    }
}
