/*
 * This file is generated by jOOQ.
 */
package com.baeldung.jooq.introduction.db.tables.records;


import com.baeldung.jooq.introduction.db.tables.FlinkPropertyByStand;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FlinkPropertyByStandRecord extends TableRecordImpl<FlinkPropertyByStandRecord> implements Record5<Object, Object, Object, Object, Object> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>LOCALDEV.FLINK_PROPERTY_BY_STAND.SERVICE_ID</code>.
     */
    public FlinkPropertyByStandRecord setServiceId(Object value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.FLINK_PROPERTY_BY_STAND.SERVICE_ID</code>.
     */
    public Object getServiceId() {
        return get(0);
    }

    /**
     * Setter for <code>LOCALDEV.FLINK_PROPERTY_BY_STAND.PROFILE_ID</code>.
     */
    public FlinkPropertyByStandRecord setProfileId(Object value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.FLINK_PROPERTY_BY_STAND.PROFILE_ID</code>.
     */
    public Object getProfileId() {
        return get(1);
    }

    /**
     * Setter for <code>LOCALDEV.FLINK_PROPERTY_BY_STAND.STAND</code>.
     */
    public FlinkPropertyByStandRecord setStand(Object value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.FLINK_PROPERTY_BY_STAND.STAND</code>.
     */
    public Object getStand() {
        return get(2);
    }

    /**
     * Setter for <code>LOCALDEV.FLINK_PROPERTY_BY_STAND.PROP_ID</code>.
     */
    public FlinkPropertyByStandRecord setPropId(Object value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.FLINK_PROPERTY_BY_STAND.PROP_ID</code>.
     */
    public Object getPropId() {
        return get(3);
    }

    /**
     * Setter for <code>LOCALDEV.FLINK_PROPERTY_BY_STAND.PROP_VALUE</code>.
     */
    public FlinkPropertyByStandRecord setPropValue(Object value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.FLINK_PROPERTY_BY_STAND.PROP_VALUE</code>.
     */
    public Object getPropValue() {
        return get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Object, Object, Object, Object, Object> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Object, Object, Object, Object, Object> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Object> field1() {
        return FlinkPropertyByStand.FLINK_PROPERTY_BY_STAND.SERVICE_ID;
    }

    @Override
    public Field<Object> field2() {
        return FlinkPropertyByStand.FLINK_PROPERTY_BY_STAND.PROFILE_ID;
    }

    @Override
    public Field<Object> field3() {
        return FlinkPropertyByStand.FLINK_PROPERTY_BY_STAND.STAND;
    }

    @Override
    public Field<Object> field4() {
        return FlinkPropertyByStand.FLINK_PROPERTY_BY_STAND.PROP_ID;
    }

    @Override
    public Field<Object> field5() {
        return FlinkPropertyByStand.FLINK_PROPERTY_BY_STAND.PROP_VALUE;
    }

    @Override
    public Object component1() {
        return getServiceId();
    }

    @Override
    public Object component2() {
        return getProfileId();
    }

    @Override
    public Object component3() {
        return getStand();
    }

    @Override
    public Object component4() {
        return getPropId();
    }

    @Override
    public Object component5() {
        return getPropValue();
    }

    @Override
    public Object value1() {
        return getServiceId();
    }

    @Override
    public Object value2() {
        return getProfileId();
    }

    @Override
    public Object value3() {
        return getStand();
    }

    @Override
    public Object value4() {
        return getPropId();
    }

    @Override
    public Object value5() {
        return getPropValue();
    }

    @Override
    public FlinkPropertyByStandRecord value1(Object value) {
        setServiceId(value);
        return this;
    }

    @Override
    public FlinkPropertyByStandRecord value2(Object value) {
        setProfileId(value);
        return this;
    }

    @Override
    public FlinkPropertyByStandRecord value3(Object value) {
        setStand(value);
        return this;
    }

    @Override
    public FlinkPropertyByStandRecord value4(Object value) {
        setPropId(value);
        return this;
    }

    @Override
    public FlinkPropertyByStandRecord value5(Object value) {
        setPropValue(value);
        return this;
    }

    @Override
    public FlinkPropertyByStandRecord values(Object value1, Object value2, Object value3, Object value4, Object value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FlinkPropertyByStandRecord
     */
    public FlinkPropertyByStandRecord() {
        super(FlinkPropertyByStand.FLINK_PROPERTY_BY_STAND);
    }

    /**
     * Create a detached, initialised FlinkPropertyByStandRecord
     */
    public FlinkPropertyByStandRecord(Object serviceId, Object profileId, Object stand, Object propId, Object propValue) {
        super(FlinkPropertyByStand.FLINK_PROPERTY_BY_STAND);

        setServiceId(serviceId);
        setProfileId(profileId);
        setStand(stand);
        setPropId(propId);
        setPropValue(propValue);
    }
}
