/*
 * This file is generated by jOOQ.
 */
package com.baeldung.jooq.introduction.db.tables.records;


import com.baeldung.jooq.introduction.db.tables.FullFlinkServicePropertyStand;

import org.jooq.Field;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FullFlinkServicePropertyStandRecord extends TableRecordImpl<FullFlinkServicePropertyStandRecord> implements Record7<Object, Object, Object, Object, Object, Object, Object> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>LOCALDEV.FULL_FLINK_SERVICE_PROPERTY_STAND.PRIORITY</code>.
     */
    public FullFlinkServicePropertyStandRecord setPriority(Object value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.FULL_FLINK_SERVICE_PROPERTY_STAND.PRIORITY</code>.
     */
    public Object getPriority() {
        return get(0);
    }

    /**
     * Setter for <code>LOCALDEV.FULL_FLINK_SERVICE_PROPERTY_STAND.SERVICE_ID</code>.
     */
    public FullFlinkServicePropertyStandRecord setServiceId(Object value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.FULL_FLINK_SERVICE_PROPERTY_STAND.SERVICE_ID</code>.
     */
    public Object getServiceId() {
        return get(1);
    }

    /**
     * Setter for <code>LOCALDEV.FULL_FLINK_SERVICE_PROPERTY_STAND.PROFILE_ID</code>.
     */
    public FullFlinkServicePropertyStandRecord setProfileId(Object value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.FULL_FLINK_SERVICE_PROPERTY_STAND.PROFILE_ID</code>.
     */
    public Object getProfileId() {
        return get(2);
    }

    /**
     * Setter for <code>LOCALDEV.FULL_FLINK_SERVICE_PROPERTY_STAND.STAND</code>.
     */
    public FullFlinkServicePropertyStandRecord setStand(Object value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.FULL_FLINK_SERVICE_PROPERTY_STAND.STAND</code>.
     */
    public Object getStand() {
        return get(3);
    }

    /**
     * Setter for <code>LOCALDEV.FULL_FLINK_SERVICE_PROPERTY_STAND.PROP_ID</code>.
     */
    public FullFlinkServicePropertyStandRecord setPropId(Object value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.FULL_FLINK_SERVICE_PROPERTY_STAND.PROP_ID</code>.
     */
    public Object getPropId() {
        return get(4);
    }

    /**
     * Setter for <code>LOCALDEV.FULL_FLINK_SERVICE_PROPERTY_STAND.PROP_VALUE</code>.
     */
    public FullFlinkServicePropertyStandRecord setPropValue(Object value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.FULL_FLINK_SERVICE_PROPERTY_STAND.PROP_VALUE</code>.
     */
    public Object getPropValue() {
        return get(5);
    }

    /**
     * Setter for <code>LOCALDEV.FULL_FLINK_SERVICE_PROPERTY_STAND.TYPE_PROPERTY</code>.
     */
    public FullFlinkServicePropertyStandRecord setTypeProperty(Object value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.FULL_FLINK_SERVICE_PROPERTY_STAND.TYPE_PROPERTY</code>.
     */
    public Object getTypeProperty() {
        return get(6);
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Object, Object, Object, Object, Object, Object, Object> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Object, Object, Object, Object, Object, Object, Object> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Object> field1() {
        return FullFlinkServicePropertyStand.FULL_FLINK_SERVICE_PROPERTY_STAND.PRIORITY;
    }

    @Override
    public Field<Object> field2() {
        return FullFlinkServicePropertyStand.FULL_FLINK_SERVICE_PROPERTY_STAND.SERVICE_ID;
    }

    @Override
    public Field<Object> field3() {
        return FullFlinkServicePropertyStand.FULL_FLINK_SERVICE_PROPERTY_STAND.PROFILE_ID;
    }

    @Override
    public Field<Object> field4() {
        return FullFlinkServicePropertyStand.FULL_FLINK_SERVICE_PROPERTY_STAND.STAND;
    }

    @Override
    public Field<Object> field5() {
        return FullFlinkServicePropertyStand.FULL_FLINK_SERVICE_PROPERTY_STAND.PROP_ID;
    }

    @Override
    public Field<Object> field6() {
        return FullFlinkServicePropertyStand.FULL_FLINK_SERVICE_PROPERTY_STAND.PROP_VALUE;
    }

    @Override
    public Field<Object> field7() {
        return FullFlinkServicePropertyStand.FULL_FLINK_SERVICE_PROPERTY_STAND.TYPE_PROPERTY;
    }

    @Override
    public Object component1() {
        return getPriority();
    }

    @Override
    public Object component2() {
        return getServiceId();
    }

    @Override
    public Object component3() {
        return getProfileId();
    }

    @Override
    public Object component4() {
        return getStand();
    }

    @Override
    public Object component5() {
        return getPropId();
    }

    @Override
    public Object component6() {
        return getPropValue();
    }

    @Override
    public Object component7() {
        return getTypeProperty();
    }

    @Override
    public Object value1() {
        return getPriority();
    }

    @Override
    public Object value2() {
        return getServiceId();
    }

    @Override
    public Object value3() {
        return getProfileId();
    }

    @Override
    public Object value4() {
        return getStand();
    }

    @Override
    public Object value5() {
        return getPropId();
    }

    @Override
    public Object value6() {
        return getPropValue();
    }

    @Override
    public Object value7() {
        return getTypeProperty();
    }

    @Override
    public FullFlinkServicePropertyStandRecord value1(Object value) {
        setPriority(value);
        return this;
    }

    @Override
    public FullFlinkServicePropertyStandRecord value2(Object value) {
        setServiceId(value);
        return this;
    }

    @Override
    public FullFlinkServicePropertyStandRecord value3(Object value) {
        setProfileId(value);
        return this;
    }

    @Override
    public FullFlinkServicePropertyStandRecord value4(Object value) {
        setStand(value);
        return this;
    }

    @Override
    public FullFlinkServicePropertyStandRecord value5(Object value) {
        setPropId(value);
        return this;
    }

    @Override
    public FullFlinkServicePropertyStandRecord value6(Object value) {
        setPropValue(value);
        return this;
    }

    @Override
    public FullFlinkServicePropertyStandRecord value7(Object value) {
        setTypeProperty(value);
        return this;
    }

    @Override
    public FullFlinkServicePropertyStandRecord values(Object value1, Object value2, Object value3, Object value4, Object value5, Object value6, Object value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FullFlinkServicePropertyStandRecord
     */
    public FullFlinkServicePropertyStandRecord() {
        super(FullFlinkServicePropertyStand.FULL_FLINK_SERVICE_PROPERTY_STAND);
    }

    /**
     * Create a detached, initialised FullFlinkServicePropertyStandRecord
     */
    public FullFlinkServicePropertyStandRecord(Object priority, Object serviceId, Object profileId, Object stand, Object propId, Object propValue, Object typeProperty) {
        super(FullFlinkServicePropertyStand.FULL_FLINK_SERVICE_PROPERTY_STAND);

        setPriority(priority);
        setServiceId(serviceId);
        setProfileId(profileId);
        setStand(stand);
        setPropId(propId);
        setPropValue(propValue);
        setTypeProperty(typeProperty);
    }
}
