/*
 * This file is generated by jOOQ.
 */
package com.baeldung.jooq.introduction.db.tables.records;


import com.baeldung.jooq.introduction.db.tables.KafkaPropertyBySevice;

import org.jooq.Field;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class KafkaPropertyBySeviceRecord extends TableRecordImpl<KafkaPropertyBySeviceRecord> implements Record7<Object, Object, Object, Object, String, Object, Object> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>LOCALDEV.KAFKA_PROPERTY_BY_SEVICE.SERVICE_ID</code>.
     */
    public KafkaPropertyBySeviceRecord setServiceId(Object value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.KAFKA_PROPERTY_BY_SEVICE.SERVICE_ID</code>.
     */
    public Object getServiceId() {
        return get(0);
    }

    /**
     * Setter for <code>LOCALDEV.KAFKA_PROPERTY_BY_SEVICE.PROFILE_ID</code>.
     */
    public KafkaPropertyBySeviceRecord setProfileId(Object value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.KAFKA_PROPERTY_BY_SEVICE.PROFILE_ID</code>.
     */
    public Object getProfileId() {
        return get(1);
    }

    /**
     * Setter for <code>LOCALDEV.KAFKA_PROPERTY_BY_SEVICE.STAND</code>.
     */
    public KafkaPropertyBySeviceRecord setStand(Object value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.KAFKA_PROPERTY_BY_SEVICE.STAND</code>.
     */
    public Object getStand() {
        return get(2);
    }

    /**
     * Setter for <code>LOCALDEV.KAFKA_PROPERTY_BY_SEVICE.PROP_ID</code>.
     */
    public KafkaPropertyBySeviceRecord setPropId(Object value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.KAFKA_PROPERTY_BY_SEVICE.PROP_ID</code>.
     */
    public Object getPropId() {
        return get(3);
    }

    /**
     * Setter for <code>LOCALDEV.KAFKA_PROPERTY_BY_SEVICE.TYPE_PROP</code>.
     */
    public KafkaPropertyBySeviceRecord setTypeProp(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.KAFKA_PROPERTY_BY_SEVICE.TYPE_PROP</code>.
     */
    public String getTypeProp() {
        return (String) get(4);
    }

    /**
     * Setter for <code>LOCALDEV.KAFKA_PROPERTY_BY_SEVICE.ENV_PROP_NAME</code>.
     */
    public KafkaPropertyBySeviceRecord setEnvPropName(Object value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.KAFKA_PROPERTY_BY_SEVICE.ENV_PROP_NAME</code>.
     */
    public Object getEnvPropName() {
        return get(5);
    }

    /**
     * Setter for <code>LOCALDEV.KAFKA_PROPERTY_BY_SEVICE.PROPERTY_VAL</code>.
     */
    public KafkaPropertyBySeviceRecord setPropertyVal(Object value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.KAFKA_PROPERTY_BY_SEVICE.PROPERTY_VAL</code>.
     */
    public Object getPropertyVal() {
        return get(6);
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Object, Object, Object, Object, String, Object, Object> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Object, Object, Object, Object, String, Object, Object> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Object> field1() {
        return KafkaPropertyBySevice.KAFKA_PROPERTY_BY_SEVICE.SERVICE_ID;
    }

    @Override
    public Field<Object> field2() {
        return KafkaPropertyBySevice.KAFKA_PROPERTY_BY_SEVICE.PROFILE_ID;
    }

    @Override
    public Field<Object> field3() {
        return KafkaPropertyBySevice.KAFKA_PROPERTY_BY_SEVICE.STAND;
    }

    @Override
    public Field<Object> field4() {
        return KafkaPropertyBySevice.KAFKA_PROPERTY_BY_SEVICE.PROP_ID;
    }

    @Override
    public Field<String> field5() {
        return KafkaPropertyBySevice.KAFKA_PROPERTY_BY_SEVICE.TYPE_PROP;
    }

    @Override
    public Field<Object> field6() {
        return KafkaPropertyBySevice.KAFKA_PROPERTY_BY_SEVICE.ENV_PROP_NAME;
    }

    @Override
    public Field<Object> field7() {
        return KafkaPropertyBySevice.KAFKA_PROPERTY_BY_SEVICE.PROPERTY_VAL;
    }

    @Override
    public Object component1() {
        return getServiceId();
    }

    @Override
    public Object component2() {
        return getProfileId();
    }

    @Override
    public Object component3() {
        return getStand();
    }

    @Override
    public Object component4() {
        return getPropId();
    }

    @Override
    public String component5() {
        return getTypeProp();
    }

    @Override
    public Object component6() {
        return getEnvPropName();
    }

    @Override
    public Object component7() {
        return getPropertyVal();
    }

    @Override
    public Object value1() {
        return getServiceId();
    }

    @Override
    public Object value2() {
        return getProfileId();
    }

    @Override
    public Object value3() {
        return getStand();
    }

    @Override
    public Object value4() {
        return getPropId();
    }

    @Override
    public String value5() {
        return getTypeProp();
    }

    @Override
    public Object value6() {
        return getEnvPropName();
    }

    @Override
    public Object value7() {
        return getPropertyVal();
    }

    @Override
    public KafkaPropertyBySeviceRecord value1(Object value) {
        setServiceId(value);
        return this;
    }

    @Override
    public KafkaPropertyBySeviceRecord value2(Object value) {
        setProfileId(value);
        return this;
    }

    @Override
    public KafkaPropertyBySeviceRecord value3(Object value) {
        setStand(value);
        return this;
    }

    @Override
    public KafkaPropertyBySeviceRecord value4(Object value) {
        setPropId(value);
        return this;
    }

    @Override
    public KafkaPropertyBySeviceRecord value5(String value) {
        setTypeProp(value);
        return this;
    }

    @Override
    public KafkaPropertyBySeviceRecord value6(Object value) {
        setEnvPropName(value);
        return this;
    }

    @Override
    public KafkaPropertyBySeviceRecord value7(Object value) {
        setPropertyVal(value);
        return this;
    }

    @Override
    public KafkaPropertyBySeviceRecord values(Object value1, Object value2, Object value3, Object value4, String value5, Object value6, Object value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached KafkaPropertyBySeviceRecord
     */
    public KafkaPropertyBySeviceRecord() {
        super(KafkaPropertyBySevice.KAFKA_PROPERTY_BY_SEVICE);
    }

    /**
     * Create a detached, initialised KafkaPropertyBySeviceRecord
     */
    public KafkaPropertyBySeviceRecord(Object serviceId, Object profileId, Object stand, Object propId, String typeProp, Object envPropName, Object propertyVal) {
        super(KafkaPropertyBySevice.KAFKA_PROPERTY_BY_SEVICE);

        setServiceId(serviceId);
        setProfileId(profileId);
        setStand(stand);
        setPropId(propId);
        setTypeProp(typeProp);
        setEnvPropName(envPropName);
        setPropertyVal(propertyVal);
    }
}
