/*
 * This file is generated by jOOQ.
 */
package com.baeldung.jooq.introduction.db.tables.records;


import com.baeldung.jooq.introduction.db.tables.ResolvablePlaceholder;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ResolvablePlaceholderRecord extends TableRecordImpl<ResolvablePlaceholderRecord> implements Record5<Object, Object, Object, Object, Object> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>LOCALDEV.RESOLVABLE_PLACEHOLDER.SERVICE_ID</code>.
     */
    public ResolvablePlaceholderRecord setServiceId(Object value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.RESOLVABLE_PLACEHOLDER.SERVICE_ID</code>.
     */
    public Object getServiceId() {
        return get(0);
    }

    /**
     * Setter for <code>LOCALDEV.RESOLVABLE_PLACEHOLDER.PROFILE_ID</code>.
     */
    public ResolvablePlaceholderRecord setProfileId(Object value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.RESOLVABLE_PLACEHOLDER.PROFILE_ID</code>.
     */
    public Object getProfileId() {
        return get(1);
    }

    /**
     * Setter for <code>LOCALDEV.RESOLVABLE_PLACEHOLDER.STAND</code>.
     */
    public ResolvablePlaceholderRecord setStand(Object value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.RESOLVABLE_PLACEHOLDER.STAND</code>.
     */
    public Object getStand() {
        return get(2);
    }

    /**
     * Setter for <code>LOCALDEV.RESOLVABLE_PLACEHOLDER.PLACEHOLDER_ID</code>.
     */
    public ResolvablePlaceholderRecord setPlaceholderId(Object value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.RESOLVABLE_PLACEHOLDER.PLACEHOLDER_ID</code>.
     */
    public Object getPlaceholderId() {
        return get(3);
    }

    /**
     * Setter for <code>LOCALDEV.RESOLVABLE_PLACEHOLDER.PLACEHOLDER_VALUE</code>.
     */
    public ResolvablePlaceholderRecord setPlaceholderValue(Object value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.RESOLVABLE_PLACEHOLDER.PLACEHOLDER_VALUE</code>.
     */
    public Object getPlaceholderValue() {
        return get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Object, Object, Object, Object, Object> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Object, Object, Object, Object, Object> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Object> field1() {
        return ResolvablePlaceholder.RESOLVABLE_PLACEHOLDER.SERVICE_ID;
    }

    @Override
    public Field<Object> field2() {
        return ResolvablePlaceholder.RESOLVABLE_PLACEHOLDER.PROFILE_ID;
    }

    @Override
    public Field<Object> field3() {
        return ResolvablePlaceholder.RESOLVABLE_PLACEHOLDER.STAND;
    }

    @Override
    public Field<Object> field4() {
        return ResolvablePlaceholder.RESOLVABLE_PLACEHOLDER.PLACEHOLDER_ID;
    }

    @Override
    public Field<Object> field5() {
        return ResolvablePlaceholder.RESOLVABLE_PLACEHOLDER.PLACEHOLDER_VALUE;
    }

    @Override
    public Object component1() {
        return getServiceId();
    }

    @Override
    public Object component2() {
        return getProfileId();
    }

    @Override
    public Object component3() {
        return getStand();
    }

    @Override
    public Object component4() {
        return getPlaceholderId();
    }

    @Override
    public Object component5() {
        return getPlaceholderValue();
    }

    @Override
    public Object value1() {
        return getServiceId();
    }

    @Override
    public Object value2() {
        return getProfileId();
    }

    @Override
    public Object value3() {
        return getStand();
    }

    @Override
    public Object value4() {
        return getPlaceholderId();
    }

    @Override
    public Object value5() {
        return getPlaceholderValue();
    }

    @Override
    public ResolvablePlaceholderRecord value1(Object value) {
        setServiceId(value);
        return this;
    }

    @Override
    public ResolvablePlaceholderRecord value2(Object value) {
        setProfileId(value);
        return this;
    }

    @Override
    public ResolvablePlaceholderRecord value3(Object value) {
        setStand(value);
        return this;
    }

    @Override
    public ResolvablePlaceholderRecord value4(Object value) {
        setPlaceholderId(value);
        return this;
    }

    @Override
    public ResolvablePlaceholderRecord value5(Object value) {
        setPlaceholderValue(value);
        return this;
    }

    @Override
    public ResolvablePlaceholderRecord values(Object value1, Object value2, Object value3, Object value4, Object value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ResolvablePlaceholderRecord
     */
    public ResolvablePlaceholderRecord() {
        super(ResolvablePlaceholder.RESOLVABLE_PLACEHOLDER);
    }

    /**
     * Create a detached, initialised ResolvablePlaceholderRecord
     */
    public ResolvablePlaceholderRecord(Object serviceId, Object profileId, Object stand, Object placeholderId, Object placeholderValue) {
        super(ResolvablePlaceholder.RESOLVABLE_PLACEHOLDER);

        setServiceId(serviceId);
        setProfileId(profileId);
        setStand(stand);
        setPlaceholderId(placeholderId);
        setPlaceholderValue(placeholderValue);
    }
}
