/*
 * This file is generated by jOOQ.
 */
package com.baeldung.jooq.introduction.db.tables.records;


import com.baeldung.jooq.introduction.db.tables.ServiceTopicNameByStand;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ServiceTopicNameByStandRecord extends TableRecordImpl<ServiceTopicNameByStandRecord> implements Record6<Object, Object, Object, Object, Object, Object> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>LOCALDEV.SERVICE_TOPIC_NAME_BY_STAND.GRAPH_ID</code>.
     */
    public ServiceTopicNameByStandRecord setGraphId(Object value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.SERVICE_TOPIC_NAME_BY_STAND.GRAPH_ID</code>.
     */
    public Object getGraphId() {
        return get(0);
    }

    /**
     * Setter for <code>LOCALDEV.SERVICE_TOPIC_NAME_BY_STAND.SERVICE_ID</code>.
     */
    public ServiceTopicNameByStandRecord setServiceId(Object value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.SERVICE_TOPIC_NAME_BY_STAND.SERVICE_ID</code>.
     */
    public Object getServiceId() {
        return get(1);
    }

    /**
     * Setter for <code>LOCALDEV.SERVICE_TOPIC_NAME_BY_STAND.PROFILE_ID</code>.
     */
    public ServiceTopicNameByStandRecord setProfileId(Object value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.SERVICE_TOPIC_NAME_BY_STAND.PROFILE_ID</code>.
     */
    public Object getProfileId() {
        return get(2);
    }

    /**
     * Setter for <code>LOCALDEV.SERVICE_TOPIC_NAME_BY_STAND.STAND</code>.
     */
    public ServiceTopicNameByStandRecord setStand(Object value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.SERVICE_TOPIC_NAME_BY_STAND.STAND</code>.
     */
    public Object getStand() {
        return get(3);
    }

    /**
     * Setter for <code>LOCALDEV.SERVICE_TOPIC_NAME_BY_STAND.PROP_ID</code>.
     */
    public ServiceTopicNameByStandRecord setPropId(Object value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.SERVICE_TOPIC_NAME_BY_STAND.PROP_ID</code>.
     */
    public Object getPropId() {
        return get(4);
    }

    /**
     * Setter for <code>LOCALDEV.SERVICE_TOPIC_NAME_BY_STAND.PROP_VALUE</code>.
     */
    public ServiceTopicNameByStandRecord setPropValue(Object value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>LOCALDEV.SERVICE_TOPIC_NAME_BY_STAND.PROP_VALUE</code>.
     */
    public Object getPropValue() {
        return get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Object, Object, Object, Object, Object, Object> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Object, Object, Object, Object, Object, Object> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Object> field1() {
        return ServiceTopicNameByStand.SERVICE_TOPIC_NAME_BY_STAND.GRAPH_ID;
    }

    @Override
    public Field<Object> field2() {
        return ServiceTopicNameByStand.SERVICE_TOPIC_NAME_BY_STAND.SERVICE_ID;
    }

    @Override
    public Field<Object> field3() {
        return ServiceTopicNameByStand.SERVICE_TOPIC_NAME_BY_STAND.PROFILE_ID;
    }

    @Override
    public Field<Object> field4() {
        return ServiceTopicNameByStand.SERVICE_TOPIC_NAME_BY_STAND.STAND;
    }

    @Override
    public Field<Object> field5() {
        return ServiceTopicNameByStand.SERVICE_TOPIC_NAME_BY_STAND.PROP_ID;
    }

    @Override
    public Field<Object> field6() {
        return ServiceTopicNameByStand.SERVICE_TOPIC_NAME_BY_STAND.PROP_VALUE;
    }

    @Override
    public Object component1() {
        return getGraphId();
    }

    @Override
    public Object component2() {
        return getServiceId();
    }

    @Override
    public Object component3() {
        return getProfileId();
    }

    @Override
    public Object component4() {
        return getStand();
    }

    @Override
    public Object component5() {
        return getPropId();
    }

    @Override
    public Object component6() {
        return getPropValue();
    }

    @Override
    public Object value1() {
        return getGraphId();
    }

    @Override
    public Object value2() {
        return getServiceId();
    }

    @Override
    public Object value3() {
        return getProfileId();
    }

    @Override
    public Object value4() {
        return getStand();
    }

    @Override
    public Object value5() {
        return getPropId();
    }

    @Override
    public Object value6() {
        return getPropValue();
    }

    @Override
    public ServiceTopicNameByStandRecord value1(Object value) {
        setGraphId(value);
        return this;
    }

    @Override
    public ServiceTopicNameByStandRecord value2(Object value) {
        setServiceId(value);
        return this;
    }

    @Override
    public ServiceTopicNameByStandRecord value3(Object value) {
        setProfileId(value);
        return this;
    }

    @Override
    public ServiceTopicNameByStandRecord value4(Object value) {
        setStand(value);
        return this;
    }

    @Override
    public ServiceTopicNameByStandRecord value5(Object value) {
        setPropId(value);
        return this;
    }

    @Override
    public ServiceTopicNameByStandRecord value6(Object value) {
        setPropValue(value);
        return this;
    }

    @Override
    public ServiceTopicNameByStandRecord values(Object value1, Object value2, Object value3, Object value4, Object value5, Object value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ServiceTopicNameByStandRecord
     */
    public ServiceTopicNameByStandRecord() {
        super(ServiceTopicNameByStand.SERVICE_TOPIC_NAME_BY_STAND);
    }

    /**
     * Create a detached, initialised ServiceTopicNameByStandRecord
     */
    public ServiceTopicNameByStandRecord(Object graphId, Object serviceId, Object profileId, Object stand, Object propId, Object propValue) {
        super(ServiceTopicNameByStand.SERVICE_TOPIC_NAME_BY_STAND);

        setGraphId(graphId);
        setServiceId(serviceId);
        setProfileId(profileId);
        setStand(stand);
        setPropId(propId);
        setPropValue(propValue);
    }
}
